<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Basic_Item_Request_TC01(old)</name>
   <tag></tag>
   <elementGuidId>30179fe4-d263-4fd8-b97d-eeb165efeeee</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>0</connectionTimeout>
   <followRedirects>true</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;\u003cSTEP-ProductInformation UseContextLocale\u003d\&quot;false\&quot; WorkspaceID\u003d\&quot;Main\&quot; ContextID\u003d\&quot;en-NZ\&quot;\u003e\n\t\u003cProducts\u003e\n\t\t\u003cProduct ParentID\u003d\&quot;${B_ParentID}\&quot; UserTypeID\u003d\&quot;PPH_BasicItem\&quot;\u003e\n\t\t\t\u003cName\u003e\n\t\t\t\t${B_Name}\n\t\t\t\u003c/Name\u003e\n\t\t\t\u003cClassificationReference Type\u003d\&quot;Product_To_BrandHierarchy\&quot;\u003e\n\t\t\t\t\u003cKeyValue KeyID\u003d\&quot;KEY_Brand\&quot;\u003e\n\t\t\t\t\tANTHEM\n\t\t\t\t\u003c/KeyValue\u003e\n\t\t\t\u003c/ClassificationReference\u003e\n\t\t\t\u003cClassificationReference Type\u003d\&quot;Product_To_MerchandiseHierarchy\&quot; ClassificationID\u003d\&quot;MERCH_L5_1308\&quot; /\u003e\n\t\t\t\u003cClassificationCrossReference Type\u003d\&quot;WSLOnlineDetails\&quot; ClassificationID\u003d\&quot;WSLHierarchy\&quot;\u003e\n\t\t\t\t\u003cMetaData\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductDescriptionWebstore\&quot;\u003e\n\t\t\t\t\t\t${B_WSL_AT_ProductDescriptionWebstore}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliveryMinimumDays\&quot;\u003e\n\t\t\t\t\t\t${B_WSL_AT_OnlineDeliveryMinimumDays}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_SoldOnlineIndicator\&quot; ID\u003d\&quot;${B_WSL_AT_SoldOnlineIndicator}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliveryMaximumDays\&quot;\u003e\n\t\t\t\t\t\t${B_WSL_AT_OnlineDeliveryMaximumDays}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebEnabled\&quot; ID\u003d\&quot;${B_WSL_AT_WebEnabled}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliverySizeOverride\&quot; ID\u003d\&quot;${B_WSL_AT_OnlineDeliverySizeOverride}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliverySizeDefault\&quot; ID\u003d\&quot;${B_WSL_AT_OnlineDeliverySizeDefault}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebItemSku\&quot;\u003e\n\t\t\t\t\t\t${B_WSL_AT_WebItemSku}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebExpiryDate\&quot;\u003e\n\t\t\t\t\t\t${B_WSL_AT_WebExpiryDate}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_FeaturesAndBenefits\&quot;\u003e\n\t\t\t\t\t\t${B_WSL_AT_FeaturesAndBenefits}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ClickAndCollectFlag\&quot; ID\u003d\&quot;${B_WSL_AT_ClickAndCollectFlag}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebClearanceIndicator\&quot; ID\u003d\&quot;${B_WSL_AT_WebClearanceIndicator}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebEffectiveDate\&quot;\u003e\n\t\t\t\t\t\t${B_WSL_AT_WebEffectiveDate}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003c/MetaData\u003e\n\t\t\t\u003c/ClassificationCrossReference\u003e\n\t\t\t\u003cClassificationCrossReference Type\u003d\&quot;TWLOnlineDetails\&quot; ClassificationID\u003d\&quot;TWLHierarchy\&quot;\u003e\n\t\t\t\t\u003cMetaData\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductDescriptionWebstore\&quot;\u003e\n\t\t\t\t\t\t${B_TWL_AT_ProductDescriptionWebstore}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliveryMinimumDays\&quot;\u003e\n\t\t\t\t\t\t${B_TWL_AT_OnlineDeliveryMinimumDays}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_SoldOnlineIndicator\&quot; ID\u003d\&quot;${B_TWL_AT_SoldOnlineIndicator}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliveryMaximumDays\&quot;\u003e\n\t\t\t\t\t\t${B_TWL_AT_OnlineDeliveryMaximumDays}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebEnabled\&quot; ID\u003d\&quot;${B_TWL_AT_WebEnabled}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliverySizeOverride\&quot; ID\u003d\&quot;${B_TWL_AT_OnlineDeliverySizeOverride}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliverySizeDefault\&quot; ID\u003d\&quot;${B_TWL_AT_OnlineDeliverySizeDefault}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebItemSku\&quot;\u003e\n\t\t\t\t\t\t${B_TWL_AT_WebItemSku}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebExpiryDate\&quot;\u003e\n\t\t\t\t\t\t${B_TWL_AT_WebExpiryDate}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_FeaturesAndBenefits\&quot;\u003e\n\t\t\t\t\t\t${B_TWL_AT_FeaturesAndBenefits}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ClickAndCollectFlag\&quot; ID\u003d\&quot;${B_TWL_AT_ClickAndCollectFlag}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebClearanceIndicator\&quot; ID\u003d\&quot;${B_TWL_AT_WebClearanceIndicator}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebEffectiveDate\&quot;\u003e\n\t\t\t\t\t\t${B_TWL_AT_WebEffectiveDate}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003c/MetaData\u003e\n\t\t\t\u003c/ClassificationCrossReference\u003e\n\t\t\t\u003cValues\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductName\&quot;\u003e\n\t\t\t\t\t${B_AT_ProductName}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductShortName\&quot;\u003e\n\t\t\t\t\t${B_AT_ProductShortName}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_DangerousGoodsTransportIndicator\&quot; ID\u003d\&quot;${B_AT_DangerousGoodsTransportIndicator}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_InStoreEndDate\&quot;\u003e\n\t\t\t\t\t${B_AT_InStoreEndDate}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_InStoreStartDate\&quot;\u003e\n\t\t\t\t\t${B_AT_InStoreStartDate}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ParallelImportCode\&quot; ID\u003d\&quot;${B_AT_ParallelImportCode}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PreOrderAvailable\&quot; ID\u003d\&quot;${B_AT_PreOrderAvailable}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductImageURLIndicator\&quot; ID\u003d\&quot;${B_AT_ProductImageURLIndicator}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_SupplierCode\&quot;\u003e\n\t\t\t\t\t${B_AT_SupplierCode}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_HighRiskIndicator\&quot; ID\u003d\&quot;${B_AT_HighRiskIndicator}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PackagingFormat\&quot; ID\u003d\&quot;${B_AT_PackagingFormat}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_RecallStatus\&quot; ID\u003d\&quot;${B_AT_RecallStatus}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductStatus\&quot; ID\u003d\&quot;${B_AT_ProductStatus}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShippingProductDepth\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t${B_AT_ShippingProductDepth}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShippingProductHeight\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t${B_AT_ShippingProductHeight}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShippingProductVolume\&quot; UnitID\u003d\&quot;unece.unit.MTQ\&quot;\u003e\n\t\t\t\t\t${B_AT_ShippingProductVolume}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShippingProductWeight\&quot; UnitID\u003d\&quot;unece.unit.KGM\&quot;\u003e\n\t\t\t\t\t${B_AT_ShippingProductWeight}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShippingProductWidth\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t${B_AT_ShippingProductWidth}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_TUIProductKey\&quot;\u003e\n\t\t\t\t\t${B_AT_TUIProductKey}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_TUIItemKey\&quot;\u003e\n\t\t\t\t\t${B_AT_TUIItemKey}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_AssetImageURL\&quot;\u003e\n\t\t\t\t\t${B_AT_AssetImageURL}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_AssemblyAttribute\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_AssemblyAttribute}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_BestBeforeDateIndicator\&quot; ID\u003d\&quot;${B_AT_BestBeforeDateIndicator}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_BetterCottonInitiative\&quot; ID\u003d\&quot;${B_AT_BetterCottonInitiative}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_Character\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_Character}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_Colour\&quot; ID\u003d\&quot;${B_AT_Colour}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ColourFamily\&quot; ID\u003d\&quot;${B_AT_ColourFamily}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ForestStewardshipCouncil\&quot; ID\u003d\&quot;${B_AT_ForestStewardshipCouncil}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_Gender\&quot; ID\u003d\&quot;${B_AT_Gender}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_License\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_License}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ReducetoSellIndicator\&quot; ID\u003d\&quot;${B_AT_ReducetoSellIndicator}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_Season\&quot; ID\u003d\&quot;${B_AT_Season}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShelfLife\&quot;\u003e\n\t\t\t\t\t${B_AT_ShelfLife}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_Size\&quot; ID\u003d\&quot;${B_AT_Size}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_SchooltexProductType\&quot;\u003e\n\t\t\t\t\t${B_AT_SchooltexProductType}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_FabricContent\&quot;\u003e\n\t\t\t\t\t${B_AT_FabricContent}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_LegalAgeRestriction\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;#{B_AT_LegalAgeRestriction}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_GSTExempt\&quot; ID\u003d\&quot;${B_AT_GSTExempt}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_SafetyCheck\&quot; ID\u003d\&quot;${B_AT_SafetyCheck}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ArtistorAuthor\&quot;\u003e\n\t\t\t\t\t${B_AT_ArtistorAuthor}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_BookGenre\&quot; ID\u003d\&quot;${B_AT_BookGenre}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_MultimediaPackSize\&quot;\u003e\n\t\t\t\t\t${B_AT_MultimediaPackSize}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_NewRelease\&quot; ID\u003d\&quot;${B_AT_NewRelease}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_NewReleaseExpiryDate\&quot;\u003e\n\t\t\t\t\t${B_AT_NewReleaseExpiryDate}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_CalculatorType\&quot; ID\u003d\&quot;${B_AT_CalculatorType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_DVDGenre\&quot; ID\u003d\&quot;${B_AT_DVDGenre}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_GameGenre\&quot; ID\u003d\&quot;${B_AT_GameGenre}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_GamingSoftwareType\&quot; ID\u003d\&quot;${B_AT_GamingSoftwareType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_HeadphoneType\&quot; ID\u003d\&quot;${B_AT_HeadphoneType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_HPSureSupplySKUCode\&quot;\u003e\n\t\t\t\t\t${B_AT_HPSureSupplySKUCode}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_iPhoneModel\&quot;\u003e\n\t\t\t\t\t${B_AT_iPhoneModel}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_MusicGenre\&quot; ID\u003d\&quot;${B_AT_MusicGenre}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OperatingSystem\&quot; ID\u003d\&quot;${B_AT_OperatingSystem}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_PrinterType\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_PrinterType}\&quot; /\u003e\n\t\t\t\t\t\u003c\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003c!-- End Category Specific TUI Atributes --\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_BedSize\&quot; ID\u003d\&quot;${B_AT_BedSize}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_BroadSpectrumCover\&quot; ID\u003d\&quot;${B_AT_BroadSpectrumCover}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_ChristmasDecorationType\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_ChristmasDecorationType}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_ChristmasDesign\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_ChristmasDesign}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ChristmasProduct\&quot; ID\u003d\&quot;${B_AT_ChristmasProduct}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_GiftOccasion\&quot; ID\u003d\&quot;${B_AT_GiftOccasion}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_GiftingRecipient\&quot; ID\u003d\&quot;${B_AT_GiftingRecipient}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductDepth\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t${B_AT_ProductDepth}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductDiameter\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t${B_AT_ProductDiameter}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductHeight\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t${B_AT_ProductHeight}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductVolume\&quot; UnitID\u003d\&quot;unece.unit.MTQ\&quot;\u003e\n\t\t\t\t\t${B_AT_ProductVolume}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductWeight\&quot; UnitID\u003d\&quot;unece.unit.KGM\&quot;\u003e\n\t\t\t\t\t${B_AT_ProductWeight}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductWidth\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t${B_AT_ProductWidth}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductLength\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t${B_AT_ProductLength}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_ProductType\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_ProductType}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_SunProtectionFactor\&quot; ID\u003d\&quot;${B_AT_SunProtectionFactor}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WarrantyPeriod\&quot; ID\u003d\&quot;${B_AT_WarrantyPeriod}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WaterResistantCover\&quot; ID\u003d\&quot;${B_AT_WaterResistantCover}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_DeliveryDate\&quot;\u003e\n\t\t\t\t\t${B_AT_DeliveryDate}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_DeliveryLocation\&quot; ID\u003d\&quot;${B_AT_DeliveryLocation}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_HalloweenProduct\&quot; ID\u003d\&quot;${B_AT_HalloweenProduct}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_PetType\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_PetType}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_CandleType\&quot; ID\u003d\&quot;${B_AT_CandleType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ChairType\&quot; ID\u003d\&quot;${B_AT_ChairType}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_CutleryType\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_CutleryType}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_DeskType\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_DeskType}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_DimensionalShape\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_DimensionalShape}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_EnergyEfficiencyRating\&quot; ID\u003d\&quot;${B_AT_EnergyEfficiencyRating}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_Ergonomic\&quot; ID\u003d\&quot;${B_AT_Ergonomic}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_FillType\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_FillType}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_FurnitureStyle\&quot; ID\u003d\&quot;${B_AT_FurnitureStyle}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_HeatingorCooling\&quot; ID\u003d\&quot;${B_AT_HeatingorCooling}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_HomeFragrance\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_HomeFragrance}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_Mattresstype\&quot; ID\u003d\&quot;${B_AT_Mattresstype}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PrintIndicator\&quot; ID\u003d\&quot;${B_AT_PrintIndicator}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_PrintorPattern\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_PrintorPattern}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_RugType\&quot; ID\u003d\&quot;${B_AT_RugType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_Table\u0026ChairSettings\&quot; ID\u003d\&quot;${B_ChairSettings}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_TowelType\&quot; ID\u003d\&quot;${B_AT_TowelType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_Usesuitability\&quot; ID\u003d\&quot;${B_AT_Usesuitability}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WaterEfficiencyRating\&quot; ID\u003d\&quot;${B_AT_WaterEfficiencyRating}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_AdditivesType\&quot; ID\u003d\&quot;${B_AT_AdditivesType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_CleaningAccessoryType\&quot; ID\u003d\&quot;${B_AT_CleaningAccessoryType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_CoverType\&quot; ID\u003d\&quot;${B_AT_CoverType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_EngineOil Type\&quot; ID\u003d\&quot;${B_AT_EngineOil}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_GPS\&quot; ID\u003d\&quot;${B_AT_GPS}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_OutdoorFurnitureMaterial\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_OutdoorFurnitureMaterial}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PaperorCardType\&quot; ID\u003d\&quot;${B_AT_PaperorCardType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PaperSize\&quot; ID\u003d\&quot;${B_AT_PaperSize}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PaperWeight\&quot; ID\u003d\&quot;${B_AT_PaperWeight}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_RollType\&quot; ID\u003d\&quot;${B_AT_RollType}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_ActivityUse\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_ActivityUse}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ArtPadType\&quot; ID\u003d\&quot;${B_AT_ArtPadType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_BookCoverType\&quot; ID\u003d\&quot;${B_AT_BookCoverType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ClipType\&quot; ID\u003d\&quot;${B_AT_ClipType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ArtPadType\&quot; ID\u003d\&quot;${B_AT_ArtPadType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_EnvelopeType\&quot; ID\u003d\&quot;${B_AT_EnvelopeType}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_ExerciseBookLineType\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_ExerciseBookLineType}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_LabelType\&quot; ID\u003d\&quot;${B_AT_LabelType}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_Material\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_Material}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PackSize\&quot; UnitID\u003d\&quot;unece.unit.PK\&quot;\u003e\n\t\t\t\t\t${B_AT_PackSize}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PaintBrushType\&quot; ID\u003d\&quot;${B_AT_PaintBrushType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PaintType\&quot; ID\u003d\&quot;${B_AT_PaintType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PenType\&quot; ID\u003d\&quot;${B_AT_PenType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PencilType\&quot; ID\u003d\&quot;${B_AT_PencilType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ReportCoverType\&quot; ID\u003d\&quot;${B_AT_ReportCoverType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_RingBinderType\&quot; ID\u003d\&quot;${B_AT_RingBinderType}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_SchoolYear\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_SchoolYear\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_SprialBound\&quot; ID\u003d\&quot;${B_AT_SprialBound}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_StampType\&quot; ID\u003d\&quot;${B_AT_StampType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_StaplerType\&quot; ID\u003d\&quot;${B_AT_StaplerType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_StationeryBookType\&quot; ID\u003d\&quot;${B_AT_StationeryBookType}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_STEAMSubject\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_STEAMSubject}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_Subject\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_Subject}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_TapeType\&quot; ID\u003d\&quot;${B_AT_TapeType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WhiteboardType\&quot; ID\u003d\&quot;${B_AT_WhiteboardType}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_CableConnections\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_CableConnections}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_ConnectionPort\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_ConnectionPort}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_DeviceType\&quot; ID\u003d\&quot;${B_AT_DeviceType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_IMEIRequired\&quot; ID\u003d\&quot;${B_AT_IMEIRequired}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_Ink\u0026TonerColours\&quot; ID\u003d\&quot;${B_AT_Ink\u0026TonerColours}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ScreenSize\&quot;\u003e\n\t\t\t\t\t${B_AT_ScreenSize}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ScreenType\&quot; ID\u003d\&quot;${B_AT_ScreenType}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_TelcoNetwork\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_TelcoNetwork}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_TouchScreen\&quot; ID\u003d\&quot;${B_AT_TouchScreen}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_Age\&quot; ID\u003d\&quot;${B_AT_Age}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ToyType\&quot; ID\u003d\&quot;${B_AT_ToyType}\&quot; /\u003e\n\t\t\t\u003c/Values\u003e\n\t\t\t\u003cDataContainers\u003e\n\t\t\t\t\u003cMultiDataContainer Type\u003d\&quot;DC_BarcodeType\&quot;\u003e\n\t\t\t\t\t\u003cDataContainer ID\u003d\&quot;${B_DC_BarcodeType}\&quot;\u003e\n\t\t\t\t\t\t\u003cValues\u003e\n\t\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductBarcode\&quot;\u003e\n\t\t\t\t\t\t\t\t${B_AT_ProductBarcode}\n\t\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_BarcodeType\&quot; ID\u003d\&quot;${B_AT_BarcodeType}\&quot;\u003e\n\t\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductBarcodeNumber\&quot;\u003e\n\t\t\t\t\t\t\t\t${B_AT_ProductBarcodeNumber}\n\t\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_BarcodeFormat\&quot; ID\u003d\&quot;UPC\&quot;\u003e\n\t\t\t\t\t\t\t\t${B_AT_BarcodeFormat}\n\t\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\u003c/Values\u003e\n\t\t\t\t\t\u003c/DataContainer\u003e\n\t\t\t\t\u003c/MultiDataContainer\u003e\n\t\t\t\u003c/DataContainers\u003e\n\t\t\u003c/Product\u003e\n\t\u003c/Products\u003e\n\u003c/STEP-ProductInformation\u003e\n&quot;,
  &quot;contentType&quot;: &quot;application/xml&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/xml</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic QVJJOjEyMzQ=</value>
   </httpHeaderProperties>
   <maxResponseSize>0</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://mdmdev.thewarehousegroup.co.nz/restapiv2/inbound-integration-endpoints/IIEP_ProductDeltaTUI/upload-and-invoke?context=en-NZ&amp;workspace=Main</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>0</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>'\r\n'</defaultValue>
      <description></description>
      <id>2e024158-dee5-4c68-a8d5-996c00aa6130</id>
      <masked>false</masked>
      <name>B_Name</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>24f427b2-dbb8-4693-930a-2a713869d417</id>
      <masked>false</masked>
      <name>B_ParentID</name>
   </variables>
   <variables>
      <defaultValue>'\r\n'</defaultValue>
      <description></description>
      <id>72940e25-7d83-4b20-8d9f-d59f491e0975</id>
      <masked>false</masked>
      <name>B_WSL_AT_ProductDescriptionWebstore</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f0335078-4e77-46a2-b3ff-670ea01a5509</id>
      <masked>false</masked>
      <name>B_WSL_AT_OnlineDeliveryMinimumDays</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6d8c8efd-163d-4b1f-85ba-e12eee10fda6</id>
      <masked>false</masked>
      <name>B_WSL_AT_SoldOnlineIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c8d7cf9a-3ea9-47f7-a8a6-80b5c46c39ce</id>
      <masked>false</masked>
      <name>B_WSL_AT_OnlineDeliveryMaximumDays</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>785d1b5f-1269-4500-9574-a46c7c5ff8b2</id>
      <masked>false</masked>
      <name>B_WSL_AT_WebEnabled</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9b3b0691-f7f1-4f69-8e56-4f5e63b393b2</id>
      <masked>false</masked>
      <name>B_WSL_AT_OnlineDeliverySizeOverride</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>86f208cd-ca3d-4ed9-bfb5-fef6d040e91a</id>
      <masked>false</masked>
      <name>B_WSL_AT_OnlineDeliverySizeDefault</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b597c6de-c022-4751-aba2-b3b3fce80e21</id>
      <masked>false</masked>
      <name>B_WSL_AT_WebItemSku</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>49a28240-8d0e-49ac-95b8-3a726ab81de9</id>
      <masked>false</masked>
      <name>B_WSL_AT_WebExpiryDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>046ee7e6-28a6-48db-9523-b3663df6c4d1</id>
      <masked>false</masked>
      <name>B_WSL_AT_FeaturesAndBenefits</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>128eae1a-5c85-49ef-a49f-da7abba33171</id>
      <masked>false</masked>
      <name>B_WSL_AT_ClickAndCollectFlag</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4df5af94-d188-4089-ab3d-d5131adf3364</id>
      <masked>false</masked>
      <name>B_WSL_AT_WebClearanceIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ac558271-4477-4785-b24e-7ccd8cf3e421</id>
      <masked>false</masked>
      <name>B_WSL_AT_WebEffectiveDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d9a3dc95-7f98-4af9-912f-1aa2f56e6e3c</id>
      <masked>false</masked>
      <name>B_TWL_AT_ProductDescriptionWebstore</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>143b659f-197c-4d6e-9b3d-686de2275266</id>
      <masked>false</masked>
      <name>B_TWL_AT_OnlineDeliveryMinimumDays</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d5a77334-4920-47bf-9812-c0a783ed5c7f</id>
      <masked>false</masked>
      <name>B_TWL_AT_SoldOnlineIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>bf6b2ac4-e9e1-40a9-8bb6-322d9c010f32</id>
      <masked>false</masked>
      <name>B_TWL_AT_OnlineDeliveryMaximumDays</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>baea04da-5a36-427a-98b3-5d39cca0f2a2</id>
      <masked>false</masked>
      <name>B_TWL_AT_WebEnabled</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e4b58752-56d5-4c70-bac1-cc01cd276f37</id>
      <masked>false</masked>
      <name>B_TWL_AT_OnlineDeliverySizeOverride</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>efd4848c-af93-413a-aca9-0615b74603b1</id>
      <masked>false</masked>
      <name>B_TWL_AT_OnlineDeliverySizeDefault</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3ad45a51-41cc-41c8-95af-e37150f2af51</id>
      <masked>false</masked>
      <name>B_TWL_AT_WebItemSku</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0a2dd5a6-3626-448a-862f-2e127c358b10</id>
      <masked>false</masked>
      <name>B_TWL_AT_WebExpiryDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ed63a1f9-c217-4e37-be90-7fc6b00b1fb2</id>
      <masked>false</masked>
      <name>B_TWL_AT_FeaturesAndBenefits</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>72c0b532-a092-4cf4-aac4-f0abfd1e500e</id>
      <masked>false</masked>
      <name>B_TWL_AT_ClickAndCollectFlag</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ec8340ea-d511-4471-98f1-5b3a673abf99</id>
      <masked>false</masked>
      <name>B_TWL_AT_WebClearanceIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>73e17882-8ed0-4f84-9034-106f3f6ef6c4</id>
      <masked>false</masked>
      <name>B_TWL_AT_WebEffectiveDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b69faf01-8f8d-4faa-b181-c11fdae39389</id>
      <masked>false</masked>
      <name>B_AT_DangerousGoodsTransportIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2a36e354-55d3-458d-a3c7-3fd3ffbee1ef</id>
      <masked>false</masked>
      <name>B_AT_HighRiskIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>5b4490b8-2002-4518-b9b8-e898d9ff48c5</id>
      <masked>false</masked>
      <name>B_AT_InStoreEndDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>235c7802-03eb-4996-9da7-56bfb6a07f8b</id>
      <masked>false</masked>
      <name>B_AT_InStoreStartDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7c79fe53-502a-4e1c-9f03-8370b5df584d</id>
      <masked>false</masked>
      <name>B_AT_PackagingFormat</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3ea36af5-48a7-4860-9414-138d1a25c4e5</id>
      <masked>false</masked>
      <name>B_AT_ParallelImportCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f2bb4cf6-1f56-4f38-a33f-65d9d6cc9abc</id>
      <masked>false</masked>
      <name>B_AT_PreOrderAvailable</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e426f365-da29-4061-b7cc-620044707fc3</id>
      <masked>false</masked>
      <name>B_AT_ProductImageURLIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>137b5e0b-5539-4039-b0f7-c52635969212</id>
      <masked>false</masked>
      <name>B_AT_ProductName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>89be1ddc-73d1-425a-a86e-087fe8442373</id>
      <masked>false</masked>
      <name>B_AT_ProductShortName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>631232a5-358f-4fe4-bad2-8d111022329d</id>
      <masked>false</masked>
      <name>B_AT_ProductStatus</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b29ebf49-a303-48e2-a8ed-a13730772397</id>
      <masked>false</masked>
      <name>B_AT_RecallStatus</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0927c7e7-0a16-45b6-9b15-130bb04a4a40</id>
      <masked>false</masked>
      <name>B_AT_ShippingProductDepth</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>65508a0d-e30a-4d69-81f9-3b3bb3ebbb6c</id>
      <masked>false</masked>
      <name>B_AT_ShippingProductHeight</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c7309bb1-62c6-49df-a631-35a7c9e7af8b</id>
      <masked>false</masked>
      <name>B_AT_ShippingProductVolume</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>5a4043cb-7810-4af4-9158-4da2424f6c5c</id>
      <masked>false</masked>
      <name>B_AT_ShippingProductWeight</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>98032c0c-0a17-4912-a05b-12aa17dafbae</id>
      <masked>false</masked>
      <name>B_AT_ShippingProductWidth</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>372d95cb-7ed3-4229-a51f-563f60ea2d07</id>
      <masked>false</masked>
      <name>B_AT_SupplierCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>81bf990a-1406-41a5-995f-ef3623df54b7</id>
      <masked>false</masked>
      <name>B_AT_TUIItemKey</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>79be888a-fa12-4ba0-b1f7-2de6e4c2f220</id>
      <masked>false</masked>
      <name>B_AT_TUIProductKey</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>18c4825b-4202-45b0-b74e-799401bc2e38</id>
      <masked>false</masked>
      <name>B_AT_AssemblyAttribute</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>01f6efaa-5a99-4e26-b7e8-b973e7c44e96</id>
      <masked>false</masked>
      <name>B_AT_BestBeforeDateIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>26f1fba6-b888-4382-96cc-e4e8fe61d4fe</id>
      <masked>false</masked>
      <name>B_AT_BetterCottonInitiative</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>173f7c88-a892-4c4c-bd55-6cec866792ea</id>
      <masked>false</masked>
      <name>B_AT_Character</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a9195d36-abb9-4239-aa27-a60fc27d9a42</id>
      <masked>false</masked>
      <name>B_AT_Colour</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2cf5f44a-bf64-415d-ab6c-ade79a4edebd</id>
      <masked>false</masked>
      <name>B_AT_ColourFamily</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e8db9aa2-dd01-45a4-ba5c-9dfd8e5874ba</id>
      <masked>false</masked>
      <name>B_AT_ForestStewardshipCouncil</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>baee9622-0783-42fb-b1c6-f44a68e85288</id>
      <masked>false</masked>
      <name>B_AT_Gender</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7405acc9-7925-45a8-a965-75c727026d88</id>
      <masked>false</masked>
      <name>B_AT_License</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>47c41bf7-e7e4-4f0e-9420-d6a2ccc121c8</id>
      <masked>false</masked>
      <name>B_AT_ReducetoSellIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>afcbb558-b361-4da7-b6bb-fc0fcce0e5f9</id>
      <masked>false</masked>
      <name>B_AT_Season</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9bf6810e-d0cc-47a7-8d32-22e5a51479e7</id>
      <masked>false</masked>
      <name>B_AT_ShelfLife</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d768a1ad-4784-4bf2-b81c-df36cd83651b</id>
      <masked>false</masked>
      <name>B_AT_Size</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ab669f0b-18df-4e3d-b951-79581a242cf8</id>
      <masked>false</masked>
      <name>B_AT_SchooltexProductType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0c9f91f5-6777-4927-940f-5686f092f0d2</id>
      <masked>false</masked>
      <name>B_AT_FabricContent</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4bd8d781-e684-47ce-9819-037fde1069bb</id>
      <masked>false</masked>
      <name>B_AT_LegalAgeRestriction</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ad7692dd-afc3-4d77-a7be-94aabfe51e06</id>
      <masked>false</masked>
      <name>B_AT_GSTExempt</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0d45b610-6719-4181-89c9-6526f36f99f8</id>
      <masked>false</masked>
      <name>B_AT_SafetyCheck</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cac3af02-a2d8-4194-9b33-226791c8dcfc</id>
      <masked>false</masked>
      <name>B_AT_ArtistorAuthor</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>42221269-47f3-43bb-bbcd-d1bc1cbe82f5</id>
      <masked>false</masked>
      <name>B_AT_BookGenre</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9e9cf38c-4813-42cb-9dab-db054e80b5af</id>
      <masked>false</masked>
      <name>B_AT_MultimediaPackSize</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>5a7649e3-42ed-4046-8cc7-6ef5a11387da</id>
      <masked>false</masked>
      <name>B_AT_NewRelease</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>475f497a-8b8a-4e0b-8f10-d8a053f0c59c</id>
      <masked>false</masked>
      <name>B_AT_NewReleaseExpiryDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>84bbe65c-0a4f-4098-8aa5-6de8f34d45ad</id>
      <masked>false</masked>
      <name>B_AT_CalculatorType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3f7d5a93-5e75-4238-95db-c29718bd55d2</id>
      <masked>false</masked>
      <name>B_AT_DVDGenre</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b8ccfa02-97a8-4fde-8c11-b09e159a1eab</id>
      <masked>false</masked>
      <name>B_AT_GameGenre</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>459856af-5d4d-42e0-a545-85f11d5076cf</id>
      <masked>false</masked>
      <name>B_AT_GamingSoftwareType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b5fa99c4-4e50-4f5f-8579-cc3171942be1</id>
      <masked>false</masked>
      <name>B_AT_HeadphoneType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4eebbc6e-2406-4496-aac6-d28916543361</id>
      <masked>false</masked>
      <name>B_AT_HPSureSupplySKUCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cfadc518-37fb-4646-bfc3-a3d2c3e6f617</id>
      <masked>false</masked>
      <name>B_AT_iPhoneModel</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>99a18164-27c2-42fe-89cf-064a30e33637</id>
      <masked>false</masked>
      <name>B_AT_MusicGenre</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>179472ae-ba95-4c6e-8396-b3de6e897180</id>
      <masked>false</masked>
      <name>B_AT_OperatingSystem</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6922fe6c-4731-4b18-a3f8-db8e57f20e7a</id>
      <masked>false</masked>
      <name>B_AT_PrinterType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c3d01893-e85a-41bc-aba0-5648861a47cd</id>
      <masked>false</masked>
      <name>B_DC_BarcodeType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1ce38b97-258e-4a7c-b597-93b3dee73073</id>
      <masked>false</masked>
      <name>B_AT_ProductBarcode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>756d16af-dfdc-44cc-a64e-c5797a30d0d6</id>
      <masked>false</masked>
      <name>B_AT_BarcodeType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>8222e724-d15b-405f-b4ab-dc8708a705cd</id>
      <masked>false</masked>
      <name>B_AT_ProductBarcodeNumber</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>63db5b0b-e40b-4adf-a158-96a613f3159f</id>
      <masked>false</masked>
      <name>B_AT_BarcodeFormat</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1ed7944f-886d-493b-b667-6b14c96d46ef</id>
      <masked>false</masked>
      <name>DangerousGoodsTransportIndicator</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()


WS.verifyResponseStatusCode(response, 200)

assertThat(response.getStatusCode()).isEqualTo(200)</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
