<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Vairant_Alone_Request_TC01</name>
   <tag></tag>
   <elementGuidId>631a8490-29cd-4223-8285-46d7de709f78</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>0</connectionTimeout>
   <followRedirects>true</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;\u003cSTEP-ProductInformation UseContextLocale\u003d\&quot;false\&quot; WorkspaceID\u003d\&quot;Main\&quot; ContextID\u003d\&quot;en-NZ\&quot;\u003e\n\t\u003cSTEP-ProductInformation ContextID\u003d\&quot;en-NZ\&quot; WorkspaceID\u003d\&quot;Main\&quot; UseContextLocale\u003d\&quot;false\&quot;\u003e\n\t\t\u003cProducts\u003e\n\t\t\t\u003cProduct UserTypeID\u003d\&quot;PPH_BasicItem\&quot; ParentID\u003d\&quot;${VA_ParentID}\&quot;\u003e\n\t\t\t\t\u003cName\u003e\n\t\t\t\t\t${VA_Name}\n\t\t\t\t\u003c/Name\u003e\n\t\t\t\t\u003cClassificationReference Type\u003d\&quot;Product_To_BrandHierarchy\&quot;\u003e\n\t\t\t\t\t\u003cKeyValue KeyID\u003d\&quot;KEY_Brand\&quot;\u003e\n\t\t\t\t\t\tANTHEM\n\t\t\t\t\t\u003c/KeyValue\u003e\n\t\t\t\t\u003c/ClassificationReference\u003e\n\t\t\t\t\u003cClassificationReference ClassificationID\u003d\&quot;MERCH_L5_1308\&quot; Type\u003d\&quot;Product_To_MerchandiseHierarchy\&quot; /\u003e\n\t\t\t\t\u003cClassificationCrossReference ClassificationID\u003d\&quot;WSLHierarchy\&quot; Type\u003d\&quot;WSLOnlineDetails\&quot;\u003e\n\t\t\t\t\t\u003cMetaData\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductDescriptionWebstore\&quot;\u003e\n\t\t\t\t\t\t\t${VA_AT_ProductDescriptionWebstore}\n\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliveryMinimumDays\&quot;\u003e\n\t\t\t\t\t\t\t${VA_AT_OnlineDeliveryMinimumDays}\n\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_SoldOnlineIndicator\&quot; ID\u003d\&quot;${VA_AT_SoldOnlineIndicator}\&quot; /\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliveryMaximumDays\&quot;\u003e\n\t\t\t\t\t\t\t${VA_AT_OnlineDeliveryMaximumDays}\n\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebEnabled\&quot; ID\u003d\&quot;${VA_AT_WebEnabled}\&quot; /\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliverySizeOverride\&quot; ID\u003d\&quot;${VA_AT_OnlineDeliverySizeOverride}\&quot; /\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliverySizeDefault\&quot; ID\u003d\&quot;${VA_AT_OnlineDeliverySizeDefault}\&quot; /\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebItemSku\&quot;\u003e\n\t\t\t\t\t\t\t${VA_AT_WebItemSku}\n\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebExpiryDate\&quot;\u003e\n\t\t\t\t\t\t\t${VA_AT_WebExpiryDate}\n\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_FeaturesAndBenefits\&quot;\u003e\n\t\t\t\t\t\t\t${VA_AT_FeaturesAndBenefits}\n\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ClickAndCollectFlag\&quot; ID\u003d\&quot;${VA_AT_ClickAndCollectFlag}\&quot; /\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebClearanceIndicator\&quot; ID\u003d\&quot;${VA_AT_WebClearanceIndicator}\&quot; /\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebEffectiveDate\&quot;\u003e\n\t\t\t\t\t\t\t${VA_AT_WebEffectiveDate}\n\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003c/MetaData\u003e\n\t\t\t\t\u003c/ClassificationCrossReference\u003e\n\t\t\t\t\u003cClassificationCrossReference ClassificationID\u003d\&quot;TWLHierarchy\&quot; Type\u003d\&quot;TWLOnlineDetails\&quot;\u003e\n\t\t\t\t\t\u003cMetaData\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductDescriptionWebstore\&quot;\u003e\n\t\t\t\t\t\t\t${VA_AT_ProductDescriptionWebstore}\n\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliveryMinimumDays\&quot;\u003e\n\t\t\t\t\t\t\t${VA_AT_OnlineDeliveryMinimumDays}\n\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_SoldOnlineIndicator\&quot; ID\u003d\&quot;${VA_AT_SoldOnlineIndicator}\&quot; /\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliveryMaximumDays\&quot;\u003e\n\t\t\t\t\t\t\t${VA_AT_OnlineDeliveryMaximumDays}\n\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebEnabled\&quot; ID\u003d\&quot;${VA_AT_WebEnabled}\&quot; /\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliverySizeOverride\&quot; ID\u003d\&quot;${VA_AT_OnlineDeliverySizeOverride}\&quot; /\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliverySizeDefault\&quot; ID\u003d\&quot;${VA_AT_OnlineDeliverySizeDefault}\&quot; /\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebItemSku\&quot;\u003e\n\t\t\t\t\t\t\t${VA_AT_WebItemSku}\n\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebExpiryDate\&quot;\u003e\n\t\t\t\t\t\t\t${VA_AT_WebExpiryDate}\n\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_FeaturesAndBenefits\&quot;\u003e\n\t\t\t\t\t\t\t${VA_AT_FeaturesAndBenefits}\n\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ClickAndCollectFlag\&quot; ID\u003d\&quot;${VA_AT_ClickAndCollectFlag}\&quot; /\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebClearanceIndicator\&quot; ID\u003d\&quot;${VA_AT_WebClearanceIndicator}\&quot; /\u003e\n\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebEffectiveDate\&quot;\u003e\n\t\t\t\t\t\t\t${VA_AT_WebEffectiveDate}\n\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003c/MetaData\u003e\n\t\t\t\t\u003c/ClassificationCrossReference\u003e\n\t\t\t\t\u003cValues\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductName\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_ProductName}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductShortName\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_ProductShortName}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_DangerousGoodsTransportIndicator\&quot; ID\u003d\&quot;${VA_AT_DangerousGoodsTransportIndicator}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_InStoreEndDate\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_InStoreEndDate}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_InStoreStartDate\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_InStoreStartDate}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductImageURLIndicator\&quot; ID\u003d\&quot;${VA_AT_ProductImageURLIndicator}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_SupplierCode\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_SupplierCode}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_HighRiskIndicator\&quot; ID\u003d\&quot;${VA_AT_HighRiskIndicator}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PackagingFormat\&quot; ID\u003d\&quot;${VA_AT_PackagingFormat}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_RecallStatus\&quot; ID\u003d\&quot;${VA_AT_RecallStatus}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductStatus\&quot; ID\u003d\&quot;${VA_AT_ProductStatus}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShippingProductDepth\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_ShippingProductDepth}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShippingProductHeight\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_ShippingProductHeight}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShippingProductVolume\&quot; UnitID\u003d\&quot;unece.unit.MTQ\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_ShippingProductVolume}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShippingProductWeight\&quot; UnitID\u003d\&quot;unece.unit.KGM\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_ShippingProductWeight}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShippingProductWidth\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_ShippingProductWidth}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_TUIProductKey\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_TUIProductKey}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_TUIItemKey\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_TUIItemKey}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_AssetImageURL\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_AssetImageURL}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_Character\&quot;\u003e\n\t\t\t\t\t\t\u003cValue ID\u003d\&quot;${VA_AT_Character}\&quot; /\u003e\n\t\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_Colour\&quot; ID\u003d\&quot;${VA_AT_Colour}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ColourFamily\&quot; ID\u003d\&quot;${VA_AT_ColourFamily}\&quot; /\u003e\n\t\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_License\&quot;\u003e\n\t\t\t\t\t\t\u003cValue ID\u003d\&quot;${VA_AT_License}\&quot; /\u003e\n\t\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_Size\&quot;\u003e\n\t\t\t\t\t\t\u003cValue ID\u003d\&quot;${VA_AT_Size}\&quot; /\u003e\n\t\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_SchooltexProductType\&quot; ID\u003d\&quot;${VA_AT_SchooltexProductType}\&quot; /\u003e\n\t\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_FabricContent\&quot;\u003e\n\t\t\t\t\t\t\u003cValue ID\u003d\&quot;${VA_AT_FabricContent}\&quot; /\u003e\n\t\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_HeadphoneType\&quot;\u003e\n\t\t\t\t\t\t\u003cValue ID\u003d\&quot;${VA_AT_HeadphoneType}\&quot; /\u003e\n\t\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_BedSize\&quot; ID\u003d\&quot;${VA_AT_BedSize}\&quot; /\u003e\n\t\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_ChristmasDecorationType\&quot;\u003e\n\t\t\t\t\t\t\u003cValue ID\u003d\&quot;${VA_AT_ChristmasDecorationType}\&quot; /\u003e\n\t\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_ChristmasDesign\&quot;\u003e\n\t\t\t\t\t\t\u003cValue ID\u003d\&quot;${VA_AT_ChristmasDesign}\&quot; /\u003e\n\t\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ChristmasProduct\&quot; ID\u003d\&quot;${VA_AT_ChristmasProduct}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductDepth\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_ProductDepth}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductDiameter\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_ProductDiameter}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductHeight\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_ProductHeight}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductVolume\&quot; UnitID\u003d\&quot;unece.unit.MTQ\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_ProductVolume}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductWeight\&quot; UnitID\u003d\&quot;unece.unit.KGM\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_ProductWeight}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductWidth\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_ProductWidth}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductLength\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_ProductLength}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_ProductType\&quot;\u003e\n\t\t\t\t\t\t\u003cValue ID\u003d\&quot;${VA_AT_ProductType}\&quot; /\u003e\n\t\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_DeliveryDate\&quot;\u003e\n\t\t\t\t\t\t${VA_AT_DeliveryDate}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_DeliveryLocation\&quot; ID\u003d\&quot;${VA_AT_DeliveryLocation}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_HalloweenProduct\&quot; ID\u003d\&quot;${VA_AT_HalloweenProduct}\&quot; /\u003e\n\t\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_PetType\&quot;\u003e\n\t\t\t\t\t\t\u003cValue ID\u003d\&quot;${VA_AT_PetType}\&quot; /\u003e\n\t\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_HomeFragrance\&quot;\u003e\n\t\t\t\t\t\t\u003cValue ID\u003d\&quot;${VA_AT_HomeFragrance}\&quot; /\u003e\n\t\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PrintIndicator\&quot; ID\u003d\&quot;${VA_AT_PrintIndicator}\&quot; /\u003e\n\t\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_PrintorPattern\&quot;\u003e\n\t\t\t\t\t\t\u003cValue ID\u003d\&quot;${VA_AT_PrintorPattern}\&quot; /\u003e\n\t\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_RugType\&quot; ID\u003d\&quot;${VA_AT_RugType}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_TowelType\&quot; ID\u003d\&quot;${VA_AT_TowelType}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PaperorCardType\&quot; ID\u003d\&quot;${VA_AT_PaperorCardType}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PaperSize\&quot; ID\u003d\&quot;${VA_AT_PaperSize}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PaperWeight\&quot; ID\u003d\&quot;${VA_AT_PaperWeight}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_RollType\&quot; ID\u003d\&quot;${VA_AT_RollType}\&quot; /\u003e\n\t\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_ActivityUse\&quot;\u003e\n\t\t\t\t\t\t\u003cValue ID\u003d\&quot;${VA_AT_ActivityUse}\&quot; /\u003e\n\t\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_CableConnections\&quot;\u003e\n\t\t\t\t\t\t\u003cValue ID\u003d\&quot;${VA_AT_CableConnections}\&quot; /\u003e\n\t\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_Ink\u0026amp;TonerColours\&quot;\u003e\n\t\t\t\t\t\t\u003cValue ID\u003d\&quot;${VA_AT_InkandTonerColours}\&quot; /\u003e\n\t\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_TelcoNetwork\&quot;\u003e\n\t\t\t\t\t\t\u003cValue ID\u003d\&quot;${VA_AT_TelcoNetwork}\&quot; /\u003e\n\t\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_Age\&quot;\u003e\n\t\t\t\t\t\t\u003cValue ID\u003d\&quot;${VA_AT_Age}\&quot; /\u003e\n\t\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003c/Values\u003e\n\t\t\t\t\u003cDataContainers\u003e\n\t\t\t\t\t\u003cMultiDataContainer Type\u003d\&quot;DC_BarcodeType\&quot;\u003e\n\t\t\t\t\t\t\u003cDataContainer ID\u003d\&quot;${VA_DC_BarcodeType}\&quot;\u003e\n\t\t\t\t\t\t\t\u003cValues\u003e\n\t\t\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductBarcode\&quot;\u003e\n\t\t\t\t\t\t\t\t\t${VA_AT_ProductBarcode}\n\t\t\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_BarcodeType\&quot; ID\u003d\&quot;P\&quot;\u003e\n\t\t\t\t\t\t\t\t\t{VA_AT_BarcodeType}\n\t\t\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductBarcodeNumber\&quot;\u003e\n\t\t\t\t\t\t\t\t\t${VA_AT_ProductBarcodeNumber}\n\t\t\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_BarcodeFormat\&quot; ID\u003d\&quot;UPC\&quot;\u003e\n\t\t\t\t\t\t\t\t\t${VA_AT_BarcodeFormat}\n\t\t\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\t\u003c/Values\u003e\n\t\t\t\t\t\t\u003c/DataContainer\u003e\n\t\t\t\t\t\u003c/MultiDataContainer\u003e\n\t\t\t\t\u003c/DataContainers\u003e\n\t\t\t\u003c/Product\u003e\n\t\t\u003c/Products\u003e\n\t\u003c/STEP-ProductInformation\u003e\n\u003c/STEP-ProductInformation\u003e\n&quot;,
  &quot;contentType&quot;: &quot;application/xml&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/octet-stream</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic QVJJOjEyMzQ=</value>
   </httpHeaderProperties>
   <maxResponseSize>0</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://mdmdev.thewarehousegroup.co.nz/restapiv2/inbound-integration-endpoints/IIEP_ProductDeltaTUI/upload-and-invoke?context=en-NZ&amp;workspace=Main</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>0</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>'\r\n'</defaultValue>
      <description></description>
      <id>2e024158-dee5-4c68-a8d5-996c00aa6130</id>
      <masked>false</masked>
      <name>VA_Name</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>24f427b2-dbb8-4693-930a-2a713869d417</id>
      <masked>false</masked>
      <name>VA_KEY_Master</name>
   </variables>
   <variables>
      <defaultValue>'\r\n'</defaultValue>
      <description></description>
      <id>72940e25-7d83-4b20-8d9f-d59f491e0975</id>
      <masked>false</masked>
      <name>VA_WSL_AT_ProductDescriptionWebstore</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f0335078-4e77-46a2-b3ff-670ea01a5509</id>
      <masked>false</masked>
      <name>VA_WSL_AT_OnlineDeliveryMinimumDays</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6d8c8efd-163d-4b1f-85ba-e12eee10fda6</id>
      <masked>false</masked>
      <name>VA_WSL_AT_SoldOnlineIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c8d7cf9a-3ea9-47f7-a8a6-80b5c46c39ce</id>
      <masked>false</masked>
      <name>VA_WSL_AT_OnlineDeliveryMaximumDays</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>785d1b5f-1269-4500-9574-a46c7c5ff8b2</id>
      <masked>false</masked>
      <name>VA_WSL_AT_WebEnabled</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9b3b0691-f7f1-4f69-8e56-4f5e63b393b2</id>
      <masked>false</masked>
      <name>VA_WSL_AT_OnlineDeliverySizeOverride</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>86f208cd-ca3d-4ed9-bfb5-fef6d040e91a</id>
      <masked>false</masked>
      <name>VA_WSL_AT_OnlineDeliverySizeDefault</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b597c6de-c022-4751-aba2-b3b3fce80e21</id>
      <masked>false</masked>
      <name>VA_WSL_AT_WebItemSku</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>49a28240-8d0e-49ac-95b8-3a726ab81de9</id>
      <masked>false</masked>
      <name>VA_WSL_AT_WebExpiryDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>046ee7e6-28a6-48db-9523-b3663df6c4d1</id>
      <masked>false</masked>
      <name>VA_WSL_AT_FeaturesAndBenefits</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>128eae1a-5c85-49ef-a49f-da7abba33171</id>
      <masked>false</masked>
      <name>VA_WSL_AT_ClickAndCollectFlag</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4df5af94-d188-4089-ab3d-d5131adf3364</id>
      <masked>false</masked>
      <name>VA_WSL_AT_WebClearanceIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ac558271-4477-4785-b24e-7ccd8cf3e421</id>
      <masked>false</masked>
      <name>VA_WSL_AT_WebEffectiveDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d9a3dc95-7f98-4af9-912f-1aa2f56e6e3c</id>
      <masked>false</masked>
      <name>VA_TWL_AT_ProductDescriptionWebstore</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>143b659f-197c-4d6e-9b3d-686de2275266</id>
      <masked>false</masked>
      <name>VA_TWL_AT_OnlineDeliveryMinimumDays</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d5a77334-4920-47bf-9812-c0a783ed5c7f</id>
      <masked>false</masked>
      <name>VA_TWL_AT_SoldOnlineIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>bf6b2ac4-e9e1-40a9-8bb6-322d9c010f32</id>
      <masked>false</masked>
      <name>VA_TWL_AT_OnlineDeliveryMaximumDays</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>baea04da-5a36-427a-98b3-5d39cca0f2a2</id>
      <masked>false</masked>
      <name>VA_TWL_AT_WebEnabled</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e4b58752-56d5-4c70-bac1-cc01cd276f37</id>
      <masked>false</masked>
      <name>VA_TWL_AT_OnlineDeliverySizeOverride</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>efd4848c-af93-413a-aca9-0615b74603b1</id>
      <masked>false</masked>
      <name>VA_TWL_AT_OnlineDeliverySizeDefault</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3ad45a51-41cc-41c8-95af-e37150f2af51</id>
      <masked>false</masked>
      <name>VA_TWL_AT_WebItemSku</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0a2dd5a6-3626-448a-862f-2e127c358b10</id>
      <masked>false</masked>
      <name>VA_TWL_AT_WebExpiryDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ed63a1f9-c217-4e37-be90-7fc6b00b1fb2</id>
      <masked>false</masked>
      <name>VA_TWL_AT_FeaturesAndBenefits</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>72c0b532-a092-4cf4-aac4-f0abfd1e500e</id>
      <masked>false</masked>
      <name>VA_TWL_AT_ClickAndCollectFlag</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ec8340ea-d511-4471-98f1-5b3a673abf99</id>
      <masked>false</masked>
      <name>VA_TWL_AT_WebClearanceIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>73e17882-8ed0-4f84-9034-106f3f6ef6c4</id>
      <masked>false</masked>
      <name>VA_TWL_AT_WebEffectiveDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>5fbb9a85-2ab7-4c7a-917d-d1ed0183abd4</id>
      <masked>false</masked>
      <name>VA_AT_ProductName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d18f4e5b-c97d-4c1c-9cf4-c60323213df5</id>
      <masked>false</masked>
      <name>VA_AT_ProductShortName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>8f5df78a-ff00-49f1-840f-6c9a61d8b77d</id>
      <masked>false</masked>
      <name>VA_AT_DangerousGoodsTransportIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>fe4d5526-33e4-4096-be17-28c16fbf4e63</id>
      <masked>false</masked>
      <name>VA_AT_InStoreEndDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d7eddfc5-b882-4ac0-9cb4-1bdf92268717</id>
      <masked>false</masked>
      <name>VA_AT_InStoreStartDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>682438f3-8d93-438a-a80e-999a522e691a</id>
      <masked>false</masked>
      <name>VA_AT_ProductImageURLIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1df8cc8a-f391-4b7c-aaf6-be2b02cf6b9c</id>
      <masked>false</masked>
      <name>VA_AT_SupplierCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e06993ee-b62b-4c9e-82c4-58fb093c5b66</id>
      <masked>false</masked>
      <name>VA_AT_HighRiskIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4c58cd87-967d-4f1c-895a-7e66d7b968ab</id>
      <masked>false</masked>
      <name>VA_AT_PackagingFormat</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0f05d0fa-e863-45fc-b7f2-e9c85fc6dc28</id>
      <masked>false</masked>
      <name>VA_AT_RecallStatus</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>37e8279a-c346-4f87-9e1c-a4c23bab5849</id>
      <masked>false</masked>
      <name>VA_AT_ProductStatus</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>55160293-b20b-4cf6-b5d3-85256d7ec14c</id>
      <masked>false</masked>
      <name>VA_AT_ShippingProductDepth</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e8fcb3de-615e-4eb1-8a5f-ca1d05e08497</id>
      <masked>false</masked>
      <name>VA_AT_ShippingProductHeight</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d06fd1e3-6f64-441a-9b87-a46ae0c434b4</id>
      <masked>false</masked>
      <name>VA_AT_ShippingProductVolume</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4775bb6e-ea8e-4e62-9781-611d730cb4c3</id>
      <masked>false</masked>
      <name>VA_AT_ShippingProductWeight</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>76c5d0c3-9d42-42db-9445-9deed2c39ad6</id>
      <masked>false</masked>
      <name>VA_AT_ShippingProductWidth</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b123b608-1e7a-465a-bcac-59ed4ec0d0c1</id>
      <masked>false</masked>
      <name>VA_AT_TUIProductKey</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7b9455c5-e8fa-481b-9338-758a644fe1f5</id>
      <masked>false</masked>
      <name>VA_AT_AssetImageURL</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>874103b6-f4de-43db-b76b-bff9b529e641</id>
      <masked>false</masked>
      <name>VA_AT_Character</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a0c42f77-e391-4982-a68c-a866970558a1</id>
      <masked>false</masked>
      <name>VA_AT_Colour</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>dd7715f9-5137-48fe-ac81-222fc198be91</id>
      <masked>false</masked>
      <name>VA_AT_ColourFamily</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ea0009f4-9905-46f9-ae1b-35b2a3ee8766</id>
      <masked>false</masked>
      <name>VA_AT_License</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d02d84df-20a6-4f6b-8f75-a2890200304d</id>
      <masked>false</masked>
      <name>VA_AT_Size</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c3a72bd4-4e31-4c03-9880-33b68686bcf5</id>
      <masked>false</masked>
      <name>VA_AT_SchooltexProductType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>fa2a2ac2-4a86-4918-9e84-50d3606b1346</id>
      <masked>false</masked>
      <name>VA_AT_FabricContent</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4f15e8b4-a977-4295-a82d-ccbdbb0d765c</id>
      <masked>false</masked>
      <name>VA_AT_HeadphoneType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>61eb2a5f-cb7a-4048-a29f-127be82f6bc8</id>
      <masked>false</masked>
      <name>VA_AT_BedSize</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>8eb9f446-f980-4df3-8059-dc379c6a2d02</id>
      <masked>false</masked>
      <name>VA_AT_ChristmasDecorationType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>8b09d43f-2caf-4fab-8204-9b921c75854e</id>
      <masked>false</masked>
      <name>VA_AT_ChristmasDesign</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0611c3ff-6176-4c6c-8fe0-9486a52be97b</id>
      <masked>false</masked>
      <name>VA_AT_ChristmasProduct</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>84564328-1583-4630-9745-698adca143eb</id>
      <masked>false</masked>
      <name>VA_AT_ProductDepth</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cb1f987b-320a-426d-b385-63d52c75a789</id>
      <masked>false</masked>
      <name>VA_AT_ProductDiameter</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3a92df7d-82e6-406b-8369-5579e6a5af10</id>
      <masked>false</masked>
      <name>VA_AT_ProductHeight</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0fd92762-fa42-4335-9462-71873ad48870</id>
      <masked>false</masked>
      <name>VA_AT_ProductVolume</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f688e319-c7b7-414e-9b61-bdb27483ed72</id>
      <masked>false</masked>
      <name>VA_AT_ProductWeight</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>68c6ce6f-8f47-490e-a5ba-b2f1b2966f29</id>
      <masked>false</masked>
      <name>VA_AT_ProductWidth</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d2e22794-95a5-470a-a11c-852a288a6583</id>
      <masked>false</masked>
      <name>VA_AT_ProductLength</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>53df88a6-8e25-4b38-b9c1-309418cb75df</id>
      <masked>false</masked>
      <name>VA_AT_ProductType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e6827082-0a8b-465c-a0ba-9c129cf440d2</id>
      <masked>false</masked>
      <name>VA_AT_DeliveryDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d3802a45-d2a2-4ce6-87fd-f859e60c80a9</id>
      <masked>false</masked>
      <name>VA_AT_DeliveryLocation</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>be42888f-00bd-4997-945b-eeebca52e2ad</id>
      <masked>false</masked>
      <name>VA_AT_HalloweenProduct</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>56eec467-dc8b-4078-b8a3-63473d0262c4</id>
      <masked>false</masked>
      <name>VA_AT_HomeFragrance</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1cc70540-953a-45c0-8171-2d1f23ce9e6a</id>
      <masked>false</masked>
      <name>VA_AT_PetType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e7bcc128-b51d-44e9-b00d-0e81b44df102</id>
      <masked>false</masked>
      <name>VA_AT_PrintIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>286604ba-b80d-459b-8399-ef0443fa6f20</id>
      <masked>false</masked>
      <name>VA_AT_PrintorPattern</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>22ef0cd4-b808-489b-957b-d04339f1a5b0</id>
      <masked>false</masked>
      <name>VA_AT_RugType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c1012777-8906-49e3-980a-69fef1a4ed59</id>
      <masked>false</masked>
      <name>VA_AT_TowelType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3ed21c9f-d153-423f-a356-fa1ecbde34ab</id>
      <masked>false</masked>
      <name>VA_AT_PaperorCardType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ce4f0f44-4273-4a83-80d5-8ec982d18236</id>
      <masked>false</masked>
      <name>VA_AT_PaperSize</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>11afae91-47d3-415a-9c3e-164a2e987b6e</id>
      <masked>false</masked>
      <name>VA_AT_PaperWeight</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>80517dc3-8db1-4e12-aba9-031ef641209c</id>
      <masked>false</masked>
      <name>VA_AT_RollType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>68b99bfc-54bc-411b-83f4-75e894e403ca</id>
      <masked>false</masked>
      <name>VA_AT_ActivityUse</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f9b6db00-f601-41c2-9e79-5b2352978b85</id>
      <masked>false</masked>
      <name>VA_AT_CableConnections</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>98fac7b1-8e92-4ba5-a80a-4d30bf7a8f4f</id>
      <masked>false</masked>
      <name>VA_AT_InkandTonerColours</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7c3b60df-f8f6-41f1-844b-e1cb069c95f6</id>
      <masked>false</masked>
      <name>VA_AT_TelcoNetwork</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d307392f-4f33-4c22-890b-7e96d7bfa60c</id>
      <masked>false</masked>
      <name>VA_AT_Age</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a65b0849-915b-4339-9f54-93b4f201e890</id>
      <masked>false</masked>
      <name>VA_DC_BarcodeType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>fd2a4228-7d4b-41d5-861a-dd3606b0bf9e</id>
      <masked>false</masked>
      <name>VA_AT_ProductBarcode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>bf9f359f-ac24-49fe-b19d-02ac325e8431</id>
      <masked>false</masked>
      <name>VA_AT_BarcodeType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>101da697-5285-4bf6-b5d8-16260f2d1c2c</id>
      <masked>false</masked>
      <name>VA_AT_ProductBarcodeNumber</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ca1d35d0-9409-47b8-b815-1a853f76c517</id>
      <masked>false</masked>
      <name>VA_AT_BarcodeFormat</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()


WS.verifyResponseStatusCode(response, 200)

assertThat(response.getStatusCode()).isEqualTo(200)</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
