<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>CI_08_CNappy_Bins_PPH_L4_105716_TC01</name>
   <tag></tag>
   <elementGuidId>f8ec2864-6b1f-4a13-8a8a-7dcb2bd03075</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>0</connectionTimeout>
   <followRedirects>true</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;\u003cSTEP-ProductInformation UseContextLocale\u003d\&quot;false\&quot; WorkspaceID\u003d\&quot;Main\&quot; ContextID\u003d\&quot;en-NZ\&quot;\u003e\n    \u003cProducts\u003e\n        \u003cProduct ParentID\u003d\&quot;${B_ParentID}\&quot; UserTypeID\u003d\&quot;PPH_BasicItem\&quot;\u003e\n            \u003cName\u003e${B_Name}\u003c/Name\u003e\n            \u003cClassificationReference Type\u003d\&quot;Product_To_BrandHierarchy\&quot;\u003e\n                \u003cKeyValue KeyID\u003d\&quot;KEY_Brand\&quot;\u003eANTHEM\u003c/KeyValue\u003e\n            \u003c/ClassificationReference\u003e\n            \u003cClassificationReference Type\u003d\&quot;Product_To_MerchandiseHierarchy\&quot; ClassificationID\u003d\&quot;MERCH_L5_1308\&quot;/\u003e\n                      \u003cClassificationCrossReference Type\u003d\&quot;WSLOnlineDetails\&quot; ClassificationID\u003d\&quot;WSLHierarchy\&quot;\u003e\n                \u003cMetaData\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_ProductDescriptionWebstore\&quot;\u003e${B_WSL_AT_ProductDescriptionWebstore}\u003c/Value\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_OnlineDeliveryMinimumDays\&quot;\u003e${B_WSL_AT_OnlineDeliveryMinimumDays}\u003c/Value\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_SoldOnlineIndicator\&quot; ID\u003d\&quot;${B_WSL_AT_SoldOnlineIndicator}\&quot;/\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_OnlineDeliveryMaximumDays\&quot;\u003e${B_WSL_AT_OnlineDeliveryMaximumDays}\u003c/Value\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_WebEnabled\&quot; ID\u003d\&quot;${B_WSL_AT_WebEnabled}\&quot;/\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_OnlineDeliverySizeOverride\&quot; ID\u003d\&quot;${B_WSL_AT_OnlineDeliverySizeOverride}\&quot;/\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_OnlineDeliverySizeDefault\&quot; ID\u003d\&quot;${B_WSL_AT_OnlineDeliverySizeDefault}\&quot;/\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_WebItemSku\&quot;\u003e${B_WSL_AT_WebItemSku}\u003c/Value\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_WebExpiryDate\&quot;\u003e${B_WSL_AT_WebExpiryDate}\u003c/Value\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_FeaturesAndBenefits\&quot;\u003e${B_WSL_AT_FeaturesAndBenefits}\u003c/Value\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_ClickAndCollectFlag\&quot; ID\u003d\&quot;${B_WSL_AT_ClickAndCollectFlag}\&quot;/\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_WebClearanceIndicator\&quot; ID\u003d\&quot;${B_WSL_AT_WebClearanceIndicator}\&quot;/\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_WebEffectiveDate\&quot;\u003e${B_WSL_AT_WebEffectiveDate}\u003c/Value\u003e\n                \u003c/MetaData\u003e\n            \u003c/ClassificationCrossReference\u003e\n\t\t\t\u003cClassificationCrossReference Type\u003d\&quot;TWLOnlineDetails\&quot; ClassificationID\u003d\&quot;TWLHierarchy\&quot;\u003e\n                \u003cMetaData\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_ProductDescriptionWebstore\&quot;\u003e${B_TWL_AT_ProductDescriptionWebstore}\u003c/Value\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_OnlineDeliveryMinimumDays\&quot;\u003e${B_TWL_AT_OnlineDeliveryMinimumDays}\u003c/Value\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_SoldOnlineIndicator\&quot; ID\u003d\&quot;${B_TWL_AT_SoldOnlineIndicator}\&quot;/\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_OnlineDeliveryMaximumDays\&quot;\u003e${B_TWL_AT_OnlineDeliveryMaximumDays}\u003c/Value\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_WebEnabled\&quot; ID\u003d\&quot;${B_TWL_AT_WebEnabled}\&quot;/\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_OnlineDeliverySizeOverride\&quot; ID\u003d\&quot;${B_TWL_AT_OnlineDeliverySizeOverride}\&quot;/\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_OnlineDeliverySizeDefault\&quot; ID\u003d\&quot;${B_TWL_AT_OnlineDeliverySizeDefault}\&quot;/\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_WebItemSku\&quot;\u003e${B_TWL_AT_WebItemSku}\u003c/Value\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_WebExpiryDate\&quot;\u003e${B_TWL_AT_WebExpiryDate}\u003c/Value\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_FeaturesAndBenefits\&quot;\u003e${B_TWL_AT_FeaturesAndBenefits}\u003c/Value\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_ClickAndCollectFlag\&quot; ID\u003d\&quot;${B_TWL_AT_ClickAndCollectFlag}\&quot;/\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_WebClearanceIndicator\&quot; ID\u003d\&quot;${B_TWL_AT_WebClearanceIndicator}\&quot;/\u003e\n                    \u003cValue AttributeID\u003d\&quot;AT_WebEffectiveDate\&quot;\u003e${B_TWL_AT_WebEffectiveDate}\u003c/Value\u003e\n                \u003c/MetaData\u003e\n            \u003c/ClassificationCrossReference\u003e\n            \u003cValues\u003e\n\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductName\&quot;\u003e${B_AT_ProductName}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ProductShortName\&quot;\u003e${B_AT_ProductShortName}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_DangerousGoodsTransportIndicator\&quot; ID\u003d\&quot;${B_AT_DangerousGoodsTransportIndicator}\&quot;/\u003e\n                \n                \u003cValue AttributeID\u003d\&quot;AT_InStoreEndDate\&quot;\u003e${B_AT_InStoreEndDate}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_InStoreStartDate\&quot;\u003e${B_AT_InStoreStartDate}\u003c/Value\u003e\n               \n                \u003cValue AttributeID\u003d\&quot;AT_ParallelImportCode\&quot; ID\u003d\&quot;${B_AT_ParallelImportCode}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_PreOrderAvailable\&quot; ID\u003d\&quot;${B_AT_PreOrderAvailable}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ProductImageURLIndicator\&quot; ID\u003d\&quot;${B_AT_ProductImageURLIndicator}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_SupplierCode\&quot;\u003e${B_AT_SupplierCode}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_HighRiskIndicator\&quot; ID\u003d\&quot;${B_AT_HighRiskIndicator}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_PackagingFormat\&quot; ID\u003d\&quot;${B_AT_PackagingFormat}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_RecallStatus\&quot; ID\u003d\&quot;${B_AT_RecallStatus}\&quot;/\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductStatus\&quot; ID\u003d\&quot;${B_AT_ProductStatus}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ShippingProductDepth\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e${B_AT_ShippingProductDepth}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ShippingProductHeight\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e${B_AT_ShippingProductHeight}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ShippingProductVolume\&quot; UnitID\u003d\&quot;unece.unit.MTQ\&quot;\u003e${B_AT_ShippingProductVolume}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ShippingProductWeight\&quot; UnitID\u003d\&quot;unece.unit.KGM\&quot;\u003e${B_AT_ShippingProductWeight}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ShippingProductWidth\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e${B_AT_ShippingProductWidth}\u003c/Value\u003e\n              \t\u003cValue AttributeID\u003d\&quot;AT_TUIProductKey\&quot;\u003e${B_AT_TUIProductKey}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_TUIItemKey\&quot;\u003e${B_AT_TUIItemKey}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_AssetImageURL\&quot;\u003e${B_AT_AssetImageURL}\u003c/Value\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_AssemblyAttribute\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_AssemblyAttribute}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_BestBeforeDateIndicator\&quot; ID\u003d\&quot;${B_AT_BestBeforeDateIndicator}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_BetterCottonInitiative\&quot; ID\u003d\&quot;${B_AT_BetterCottonInitiative}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_Character\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_Character}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_Colour\&quot; ID\u003d\&quot;${B_AT_Colour}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ColourFamily\&quot; ID\u003d\&quot;${B_AT_ColourFamily}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ForestStewardshipCouncil\&quot; ID\u003d\&quot;${B_AT_ForestStewardshipCouncil}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_Gender\&quot; ID\u003d\&quot;${B_AT_Gender}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_License\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_License}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ReducetoSellIndicator\&quot; ID\u003d\&quot;${B_AT_ReducetoSellIndicator}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_Season\&quot; ID\u003d\&quot;${B_AT_Season}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ShelfLife\&quot;\u003e${B_AT_ShelfLife}\u003c/Value\u003e\n               \u003cMultiValue AttributeID\u003d\&quot;AT_Size\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_Size}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_SchooltexProductType\&quot;\u003e${B_AT_SchooltexProductType}\u003c/Value\u003e\n              \u003cMultiValue AttributeID\u003d\&quot;AT_FabricContent\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_FabricContent}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_LegalAgeRestriction\&quot; ID\u003d\&quot;${B_AT_LegalAgeRestriction}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_GSTExempt\&quot; ID\u003d\&quot;${B_AT_GSTExempt}\&quot;/\u003e\n                \n                \u003cValue AttributeID\u003d\&quot;AT_ArtistorAuthor\&quot;\u003e${B_AT_ArtistorAuthor}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_BookGenre\&quot; ID\u003d\&quot;${B_AT_BookGenre}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_MultimediaPackSize\&quot;\u003e${B_AT_MultimediaPackSize}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_NewRelease\&quot; ID\u003d\&quot;${B_AT_NewRelease}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_NewReleaseExpiryDate\&quot;\u003e${B_AT_NewReleaseExpiryDate}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_CalculatorType\&quot; ID\u003d\&quot;${B_AT_CalculatorType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_DVDGenre\&quot; ID\u003d\&quot;${B_AT_DVDGenre}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_GameGenre\&quot; ID\u003d\&quot;${B_AT_GameGenre}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_GamingSoftwareType\&quot; ID\u003d\&quot;${B_AT_GamingSoftwareType}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_HeadphoneType\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_HeadphoneType}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_HPSureSupplySKUCode\&quot;\u003e${B_AT_HPSureSupplySKUCode}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_iPhoneModel\&quot;\u003e${B_AT_iPhoneModel}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_MusicGenre\&quot; ID\u003d\&quot;${B_AT_MusicGenre}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_OperatingSystem\&quot; ID\u003d\&quot;${B_AT_OperatingSystem}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_PrinterType\&quot;\u003e\n\t\t\t\t\u003cValue ID\u003d\&quot;${B_AT_PrinterType}\&quot;/\u003e\n                   \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_BedSize\&quot; ID\u003d\&quot;${B_AT_BedSize}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_BroadSpectrumCover\&quot; ID\u003d\&quot;${B_AT_BroadSpectrumCover}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_ChristmasDecorationType\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_ChristmasDecorationType}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_ChristmasDesign\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_ChristmasDesign}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ChristmasProduct\&quot; ID\u003d\&quot;${B_AT_ChristmasProduct}\&quot;/\u003e\n              \u003cMultiValue AttributeID\u003d\&quot;AT_GiftOccasion\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_GiftOccasion}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n               \u003cMultiValue AttributeID\u003d\&quot;AT_GiftingRecipient\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_GiftingRecipient}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n              \n                \u003cValue AttributeID\u003d\&quot;AT_ProductDepth\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e${B_AT_ProductDepth}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ProductDiameter\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e${B_AT_ProductDiameter}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ProductHeight\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e${B_AT_ProductHeight}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ProductVolume\&quot; UnitID\u003d\&quot;unece.unit.MTQ\&quot;\u003e${B_AT_ProductVolume}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ProductWeight\&quot; UnitID\u003d\&quot;unece.unit.KGM\&quot;\u003e${B_AT_ProductWeight}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ProductWidth\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e${B_AT_ProductWidth}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ProductLength\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e${B_AT_ProductLength}\u003c/Value\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_ProductType\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_ProductType}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_SunProtectionFactor\&quot; ID\u003d\&quot;${B_AT_SunProtectionFactor}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_WarrantyPeriod\&quot; ID\u003d\&quot;${B_AT_WarrantyPeriod}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_WaterResistantCover\&quot; ID\u003d\&quot;${B_AT_WaterResistantCover}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_DeliveryDate\&quot;\u003e${B_AT_DeliveryDate}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_DeliveryLocation\&quot; ID\u003d\&quot;${B_AT_DeliveryLocation}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_HalloweenProduct\&quot; ID\u003d\&quot;${B_AT_HalloweenProduct}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_PetType\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_PetType}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_CandleType\&quot; ID\u003d\&quot;${B_AT_CandleType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ChairType\&quot; ID\u003d\&quot;${B_AT_ChairType}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_CutleryType\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_CutleryType}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_DeskType\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_DeskType}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_DimensionalShape\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_DimensionalShape}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_EnergyEfficiencyRating\&quot; ID\u003d\&quot;${B_AT_EnergyEfficiencyRating}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_Ergonomic\&quot; ID\u003d\&quot;${B_AT_Ergonomic}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_FillType\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_FillType}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_FurnitureStyle\&quot; ID\u003d\&quot;${B_AT_FurnitureStyle}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_HeatingorCooling\&quot; ID\u003d\&quot;${B_AT_HeatingorCooling}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_HomeFragrance\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_HomeFragrance}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_Mattresstype\&quot; ID\u003d\&quot;${B_AT_Mattresstype}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_PrintIndicator\&quot; ID\u003d\&quot;${B_AT_PrintIndicator}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_PrintorPattern\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_PrintorPattern}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_RugType\&quot; ID\u003d\&quot;${B_AT_RugType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_Table\u0026amp;ChairSettings\&quot; ID\u003d\&quot;${B_AT_TableandChairSettings}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_TowelType\&quot; ID\u003d\&quot;${B_AT_TowelType}\&quot;/\u003e\n              \u003cMultiValue AttributeID\u003d\&quot;AT_Usesuitability\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_Usesuitability}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_WaterEfficiencyRating\&quot; ID\u003d\&quot;${B_AT_WaterEfficiencyRating}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_AdditivesType\&quot; ID\u003d\&quot;${B_AT_AdditivesType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_CleaningAccessoryType\&quot; ID\u003d\&quot;${B_AT_CleaningAccessoryType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_CoverType\&quot; ID\u003d\&quot;${B_AT_CoverType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_EngineOil Type\&quot; ID\u003d\&quot;${B_AT_EngineOilType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_GPS\&quot; ID\u003d\&quot;${B_AT_GPS}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_OutdoorFurnitureMaterial\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_OutdoorFurnitureMaterial}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_PaperorCardType\&quot; ID\u003d\&quot;${B_AT_PaperorCardType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_PaperSize\&quot; ID\u003d\&quot;${B_AT_PaperSize}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_PaperWeight\&quot; ID\u003d\&quot;${B_AT_PaperWeight}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_RollType\&quot; ID\u003d\&quot;${B_AT_RollType}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_ActivityUse\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_ActivityUse}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ArtPadType\&quot; ID\u003d\&quot;${B_AT_ArtPadType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_BookCoverType\&quot; ID\u003d\&quot;${B_AT_BookCoverType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ClipType\&quot; ID\u003d\&quot;${B_AT_ClipType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_EnvelopeType\&quot; ID\u003d\&quot;${B_AT_EnvelopeType}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_ExerciseBookLineType\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_ExerciseBookLineType}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_LabelType\&quot; ID\u003d\&quot;${B_AT_LabelType}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_Material\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_Material}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_PackSize\&quot; UnitID\u003d\&quot;unece.unit.PK\&quot;\u003e${B_AT_PackSize}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_PaintBrushType\&quot; ID\u003d\&quot;${B_AT_PaintBrushType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_PaintType\&quot; ID\u003d\&quot;${B_AT_PaintType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_PenType\&quot; ID\u003d\&quot;${B_AT_PenType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_PencilType\&quot; ID\u003d\&quot;${B_AT_PencilType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ReportCoverType\&quot; ID\u003d\&quot;${B_AT_ReportCoverType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_RingBinderType\&quot; ID\u003d\&quot;${B_AT_RingBinderType}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_SchoolYear\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_SchoolYear\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_SprialBound\&quot; ID\u003d\&quot;${B_AT_SprialBound}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_StampType\&quot; ID\u003d\&quot;${B_AT_StampType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_StaplerType\&quot; ID\u003d\&quot;${B_AT_StaplerType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_StationeryBookType\&quot; ID\u003d\&quot;${B_AT_StationeryBookType}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_STEAMSubject\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_STEAMSubject}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_Subject\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_Subject}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_TapeType\&quot; ID\u003d\&quot;${B_AT_TapeType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_WhiteboardType\&quot; ID\u003d\&quot;${B_AT_WhiteboardType}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_CableConnections\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_CableConnections}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_ConnectionPort\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_ConnectionPort}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_DeviceType\&quot; ID\u003d\&quot;${B_AT_DeviceType}\&quot;/\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_IMEIRequired\&quot; ID\u003d\&quot;${B_AT_IMEIRequired}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_Ink\u0026amp;TonerColours\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_InkandTonerColours}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ScreenSize\&quot;\u003e${B_AT_ScreenSize}\u003c/Value\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ScreenType\&quot; ID\u003d\&quot;${B_AT_ScreenType}\&quot;/\u003e\n                \u003cMultiValue AttributeID\u003d\&quot;AT_TelcoNetwork\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_TelcoNetwork}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_TouchScreen\&quot; ID\u003d\&quot;${B_AT_TouchScreen}\&quot;/\u003e\n               \u003cMultiValue AttributeID\u003d\&quot;AT_Age\&quot;\u003e\n                    \u003cValue ID\u003d\&quot;${B_AT_Age}\&quot;/\u003e\n                \u003c/MultiValue\u003e\n                \u003cValue AttributeID\u003d\&quot;AT_ToyType\&quot; ID\u003d\&quot;${B_AT_ToyType}\&quot; /\u003e\n            \u003c/Values\u003e\n            \u003cDataContainers\u003e\n                \u003cMultiDataContainer Type\u003d\&quot;DC_BarcodeType\&quot;\u003e\n                    \u003cDataContainer ID\u003d\&quot;${B_BarCode_Name}\&quot;\u003e\n                                \u003cValues\u003e\n                                    \u003cValue AttributeID\u003d\&quot;AT_ProductBarcode\&quot;\u003e${B_AT_ProductBarcode}\u003c/Value\u003e\n                                    \u003cValue AttributeID\u003d\&quot;AT_ProductBarcodeNumber\&quot;\u003e${B_AT_ProductBarcodeNumber}\u003c/Value\u003e\n                                    \u003cValue AttributeID\u003d\&quot;AT_BarcodeFormat\&quot; ID\u003d\&quot;${B_AT_BarcodeFormat}\&quot; /\u003e\n                                  \t\u003cValue AttributeID\u003d\&quot;AT_BarcodeType\&quot; ID\u003d\&quot;${B_AT_BarcodeType}\&quot; /\u003e\n                                \u003c/Values\u003e\n                            \u003c/DataContainer\u003e\n              \n                   \u003c/MultiDataContainer\u003e\n                \u003c/DataContainers\u003e\n              \u003c/Product\u003e\n            \u003c/Products\u003e\n        \u003c/STEP-ProductInformation\u003e&quot;,
  &quot;contentType&quot;: &quot;application/xml&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/octet-stream</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic QVJJOjEyMzQ=</value>
   </httpHeaderProperties>
   <maxResponseSize>0</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://mdmdev.thewarehousegroup.co.nz/restapiv2/inbound-integration-endpoints/IIEP_ProductDeltaTUI/upload-and-invoke?context=en-NZ&amp;workspace=Main</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>0</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>'\r\n'</defaultValue>
      <description></description>
      <id>2e024158-dee5-4c68-a8d5-996c00aa6130</id>
      <masked>false</masked>
      <name>B_Name</name>
   </variables>
   <variables>
      <defaultValue>null</defaultValue>
      <description></description>
      <id>24f427b2-dbb8-4693-930a-2a713869d417</id>
      <masked>false</masked>
      <name>B_ParentID</name>
   </variables>
   <variables>
      <defaultValue>'\r\n'</defaultValue>
      <description></description>
      <id>72940e25-7d83-4b20-8d9f-d59f491e0975</id>
      <masked>false</masked>
      <name>B_WSL_AT_ProductDescriptionWebstore</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f0335078-4e77-46a2-b3ff-670ea01a5509</id>
      <masked>false</masked>
      <name>B_WSL_AT_OnlineDeliveryMinimumDays</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6d8c8efd-163d-4b1f-85ba-e12eee10fda6</id>
      <masked>false</masked>
      <name>B_WSL_AT_SoldOnlineIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c8d7cf9a-3ea9-47f7-a8a6-80b5c46c39ce</id>
      <masked>false</masked>
      <name>B_WSL_AT_OnlineDeliveryMaximumDays</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>785d1b5f-1269-4500-9574-a46c7c5ff8b2</id>
      <masked>false</masked>
      <name>B_WSL_AT_WebEnabled</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9b3b0691-f7f1-4f69-8e56-4f5e63b393b2</id>
      <masked>false</masked>
      <name>B_WSL_AT_OnlineDeliverySizeOverride</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>86f208cd-ca3d-4ed9-bfb5-fef6d040e91a</id>
      <masked>false</masked>
      <name>B_WSL_AT_OnlineDeliverySizeDefault</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b597c6de-c022-4751-aba2-b3b3fce80e21</id>
      <masked>false</masked>
      <name>B_WSL_AT_WebItemSku</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>49a28240-8d0e-49ac-95b8-3a726ab81de9</id>
      <masked>false</masked>
      <name>B_WSL_AT_WebExpiryDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>046ee7e6-28a6-48db-9523-b3663df6c4d1</id>
      <masked>false</masked>
      <name>B_WSL_AT_FeaturesAndBenefits</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>128eae1a-5c85-49ef-a49f-da7abba33171</id>
      <masked>false</masked>
      <name>B_WSL_AT_ClickAndCollectFlag</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4df5af94-d188-4089-ab3d-d5131adf3364</id>
      <masked>false</masked>
      <name>B_WSL_AT_WebClearanceIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ac558271-4477-4785-b24e-7ccd8cf3e421</id>
      <masked>false</masked>
      <name>B_WSL_AT_WebEffectiveDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d9a3dc95-7f98-4af9-912f-1aa2f56e6e3c</id>
      <masked>false</masked>
      <name>B_TWL_AT_ProductDescriptionWebstore</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>143b659f-197c-4d6e-9b3d-686de2275266</id>
      <masked>false</masked>
      <name>B_TWL_AT_OnlineDeliveryMinimumDays</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d5a77334-4920-47bf-9812-c0a783ed5c7f</id>
      <masked>false</masked>
      <name>B_TWL_AT_SoldOnlineIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>bf6b2ac4-e9e1-40a9-8bb6-322d9c010f32</id>
      <masked>false</masked>
      <name>B_TWL_AT_OnlineDeliveryMaximumDays</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>baea04da-5a36-427a-98b3-5d39cca0f2a2</id>
      <masked>false</masked>
      <name>B_TWL_AT_WebEnabled</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e4b58752-56d5-4c70-bac1-cc01cd276f37</id>
      <masked>false</masked>
      <name>B_TWL_AT_OnlineDeliverySizeOverride</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>efd4848c-af93-413a-aca9-0615b74603b1</id>
      <masked>false</masked>
      <name>B_TWL_AT_OnlineDeliverySizeDefault</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3ad45a51-41cc-41c8-95af-e37150f2af51</id>
      <masked>false</masked>
      <name>B_TWL_AT_WebItemSku</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0a2dd5a6-3626-448a-862f-2e127c358b10</id>
      <masked>false</masked>
      <name>B_TWL_AT_WebExpiryDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ed63a1f9-c217-4e37-be90-7fc6b00b1fb2</id>
      <masked>false</masked>
      <name>B_TWL_AT_FeaturesAndBenefits</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>72c0b532-a092-4cf4-aac4-f0abfd1e500e</id>
      <masked>false</masked>
      <name>B_TWL_AT_ClickAndCollectFlag</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ec8340ea-d511-4471-98f1-5b3a673abf99</id>
      <masked>false</masked>
      <name>B_TWL_AT_WebClearanceIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>73e17882-8ed0-4f84-9034-106f3f6ef6c4</id>
      <masked>false</masked>
      <name>B_TWL_AT_WebEffectiveDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>137b5e0b-5539-4039-b0f7-c52635969212</id>
      <masked>false</masked>
      <name>B_AT_ProductName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>89be1ddc-73d1-425a-a86e-087fe8442373</id>
      <masked>false</masked>
      <name>B_AT_ProductShortName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b69faf01-8f8d-4faa-b181-c11fdae39389</id>
      <masked>false</masked>
      <name>B_AT_DangerousGoodsTransportIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>5b4490b8-2002-4518-b9b8-e898d9ff48c5</id>
      <masked>false</masked>
      <name>B_AT_InStoreEndDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>235c7802-03eb-4996-9da7-56bfb6a07f8b</id>
      <masked>false</masked>
      <name>B_AT_InStoreStartDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3ea36af5-48a7-4860-9414-138d1a25c4e5</id>
      <masked>false</masked>
      <name>B_AT_ParallelImportCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f2bb4cf6-1f56-4f38-a33f-65d9d6cc9abc</id>
      <masked>false</masked>
      <name>B_AT_PreOrderAvailable </name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e426f365-da29-4061-b7cc-620044707fc3</id>
      <masked>false</masked>
      <name>B_AT_ProductImageURLIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>372d95cb-7ed3-4229-a51f-563f60ea2d07</id>
      <masked>false</masked>
      <name>B_AT_SupplierCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2a36e354-55d3-458d-a3c7-3fd3ffbee1ef</id>
      <masked>false</masked>
      <name>B_AT_HighRiskIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>631232a5-358f-4fe4-bad2-8d111022329d</id>
      <masked>false</masked>
      <name>B_AT_PackagingFormat</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b29ebf49-a303-48e2-a8ed-a13730772397</id>
      <masked>false</masked>
      <name>B_AT_RecallStatus</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9aac9f77-e19d-4b51-a167-bcd7a3884e31</id>
      <masked>false</masked>
      <name>B_AT_ProductStatus</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0927c7e7-0a16-45b6-9b15-130bb04a4a40</id>
      <masked>false</masked>
      <name>B_AT_ShippingProductDepth</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>65508a0d-e30a-4d69-81f9-3b3bb3ebbb6c</id>
      <masked>false</masked>
      <name>B_AT_ShippingProductHeight</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c7309bb1-62c6-49df-a631-35a7c9e7af8b</id>
      <masked>false</masked>
      <name>B_AT_ShippingProductVolume</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>5a4043cb-7810-4af4-9158-4da2424f6c5c</id>
      <masked>false</masked>
      <name>B_AT_ShippingProductWeight</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>98032c0c-0a17-4912-a05b-12aa17dafbae</id>
      <masked>false</masked>
      <name>B_AT_ShippingProductWidth</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>79be888a-fa12-4ba0-b1f7-2de6e4c2f220</id>
      <masked>false</masked>
      <name>B_AT_TUIProductKey</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>81bf990a-1406-41a5-995f-ef3623df54b7</id>
      <masked>false</masked>
      <name>B_AT_TUIItemKey</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4203fb58-9d7c-4a08-9917-14791276d04e</id>
      <masked>false</masked>
      <name>B_AT_AssetImageURL</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>18c4825b-4202-45b0-b74e-799401bc2e38</id>
      <masked>false</masked>
      <name>B_AT_AssemblyAttribute</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>01f6efaa-5a99-4e26-b7e8-b973e7c44e96</id>
      <masked>false</masked>
      <name>B_AT_BestBeforeDateIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>26f1fba6-b888-4382-96cc-e4e8fe61d4fe</id>
      <masked>false</masked>
      <name>B_AT_BetterCottonInitiative</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>173f7c88-a892-4c4c-bd55-6cec866792ea</id>
      <masked>false</masked>
      <name>B_AT_Character</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a9195d36-abb9-4239-aa27-a60fc27d9a42</id>
      <masked>false</masked>
      <name>B_AT_Colour</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2cf5f44a-bf64-415d-ab6c-ade79a4edebd</id>
      <masked>false</masked>
      <name>B_AT_ColourFamily</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e8db9aa2-dd01-45a4-ba5c-9dfd8e5874ba</id>
      <masked>false</masked>
      <name>B_AT_ForestStewardshipCouncil</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>baee9622-0783-42fb-b1c6-f44a68e85288</id>
      <masked>false</masked>
      <name>B_AT_Gender</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7405acc9-7925-45a8-a965-75c727026d88</id>
      <masked>false</masked>
      <name>B_AT_License</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>47c41bf7-e7e4-4f0e-9420-d6a2ccc121c8</id>
      <masked>false</masked>
      <name>B_AT_ReducetoSellIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>afcbb558-b361-4da7-b6bb-fc0fcce0e5f9</id>
      <masked>false</masked>
      <name>B_AT_Season</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9bf6810e-d0cc-47a7-8d32-22e5a51479e7</id>
      <masked>false</masked>
      <name>B_AT_ShelfLife</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d768a1ad-4784-4bf2-b81c-df36cd83651b</id>
      <masked>false</masked>
      <name>B_AT_Size</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ab669f0b-18df-4e3d-b951-79581a242cf8</id>
      <masked>false</masked>
      <name>B_AT_SchooltexProductType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0c9f91f5-6777-4927-940f-5686f092f0d2</id>
      <masked>false</masked>
      <name>B_AT_FabricContent</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4bd8d781-e684-47ce-9819-037fde1069bb</id>
      <masked>false</masked>
      <name>B_AT_LegalAgeRestriction</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ad7692dd-afc3-4d77-a7be-94aabfe51e06</id>
      <masked>false</masked>
      <name>B_AT_GSTExempt</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cac3af02-a2d8-4194-9b33-226791c8dcfc</id>
      <masked>false</masked>
      <name>B_AT_ArtistorAuthor</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>42221269-47f3-43bb-bbcd-d1bc1cbe82f5</id>
      <masked>false</masked>
      <name>B_AT_BookGenre</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9e9cf38c-4813-42cb-9dab-db054e80b5af</id>
      <masked>false</masked>
      <name>B_AT_MultimediaPackSize</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>5a7649e3-42ed-4046-8cc7-6ef5a11387da</id>
      <masked>false</masked>
      <name>B_AT_NewRelease</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>475f497a-8b8a-4e0b-8f10-d8a053f0c59c</id>
      <masked>false</masked>
      <name>B_AT_NewReleaseExpiryDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>84bbe65c-0a4f-4098-8aa5-6de8f34d45ad</id>
      <masked>false</masked>
      <name>B_AT_CalculatorType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3f7d5a93-5e75-4238-95db-c29718bd55d2</id>
      <masked>false</masked>
      <name>B_AT_DVDGenre</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b8ccfa02-97a8-4fde-8c11-b09e159a1eab</id>
      <masked>false</masked>
      <name>B_AT_GameGenre</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>459856af-5d4d-42e0-a545-85f11d5076cf</id>
      <masked>false</masked>
      <name>B_AT_GamingSoftwareType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b5fa99c4-4e50-4f5f-8579-cc3171942be1</id>
      <masked>false</masked>
      <name>B_AT_HeadphoneType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4eebbc6e-2406-4496-aac6-d28916543361</id>
      <masked>false</masked>
      <name>B_AT_HPSureSupplySKUCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cfadc518-37fb-4646-bfc3-a3d2c3e6f617</id>
      <masked>false</masked>
      <name>B_AT_iPhoneModel</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>99a18164-27c2-42fe-89cf-064a30e33637</id>
      <masked>false</masked>
      <name>B_AT_MusicGenre</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>179472ae-ba95-4c6e-8396-b3de6e897180</id>
      <masked>false</masked>
      <name>B_AT_OperatingSystem</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6922fe6c-4731-4b18-a3f8-db8e57f20e7a</id>
      <masked>false</masked>
      <name>B_AT_PrinterType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1e246bb8-977f-48c5-a4cb-10b6c28e5abf</id>
      <masked>false</masked>
      <name>B_AT_BedSize</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cfd018bd-23bd-40b3-873a-ea651f0ee7bc</id>
      <masked>false</masked>
      <name>B_AT_BroadSpectrumCover</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4ba696f3-e688-45ba-907a-c60584d15ed3</id>
      <masked>false</masked>
      <name>B_AT_ChristmasDecorationType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2f42126a-c2fa-4da8-b4af-0c7da1fee34b</id>
      <masked>false</masked>
      <name>B_AT_ChristmasDesign</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>123ee307-a680-4e52-a26e-d7c67868dc62</id>
      <masked>false</masked>
      <name>B_AT_ChristmasProduct</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e947fe9d-8e9e-45b5-8d65-05836a89811e</id>
      <masked>false</masked>
      <name>B_AT_GiftOccasion</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9e3f0739-6f63-4444-95db-c4337850a703</id>
      <masked>false</masked>
      <name>B_AT_GiftingRecipient</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>78b050c6-81c9-427b-994a-682db690a154</id>
      <masked>false</masked>
      <name>B_AT_ProductDepth</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>92eb1a45-2c71-499f-9d25-326919382570</id>
      <masked>false</masked>
      <name>B_AT_ProductDiameter</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>56e9cf51-18b0-4bc5-b44d-96700f8db394</id>
      <masked>false</masked>
      <name>B_AT_ProductHeight</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>39ac08f4-17f0-481e-b7dc-b513cb4294e0</id>
      <masked>false</masked>
      <name>B_AT_ProductLength</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>caa1855a-6b11-42b4-a8ee-b8bbcaaaf36a</id>
      <masked>false</masked>
      <name>B_AT_ProductType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>36cbab4d-df28-4c62-b853-f1dcf3616c36</id>
      <masked>false</masked>
      <name>B_AT_ProductVolume</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cd71615d-3d14-4475-8f5e-226794dc10cb</id>
      <masked>false</masked>
      <name>B_AT_ProductWeight</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0c5b9dc0-3192-48ab-b616-df676f1eb0da</id>
      <masked>false</masked>
      <name>B_AT_ProductWidth</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d9f517af-90db-49b5-a9c6-ca18ea7f311f</id>
      <masked>false</masked>
      <name>B_AT_SunProtectionFactor</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>428f4c6b-bf7a-4906-991b-d8c4ee760656</id>
      <masked>false</masked>
      <name>B_AT_WarrantyPeriod</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>845c67ff-0718-4fc3-8e50-60e42d2d93c3</id>
      <masked>false</masked>
      <name>B_AT_WaterResistantCover</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ca486c72-f515-48b5-82a3-448b32594eba</id>
      <masked>false</masked>
      <name>B_AT_DeliveryDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c7594382-0647-4c53-af7d-8856f4de2920</id>
      <masked>false</masked>
      <name>B_AT_DeliveryLocation</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d2af87b2-0cea-4320-b8d6-c3a1a288aa62</id>
      <masked>false</masked>
      <name>B_AT_HalloweenProduct</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ab6db570-883d-4ff2-9f79-10fce358219d</id>
      <masked>false</masked>
      <name>B_AT_PetType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4e59fcd5-ce81-49c2-8da6-93d2425a2bb1</id>
      <masked>false</masked>
      <name>B_AT_CandleType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6a393489-29e4-4d9a-93fd-1dfde59b9d29</id>
      <masked>false</masked>
      <name>B_AT_ChairType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>88fd1472-b982-498d-8282-8d30b62690aa</id>
      <masked>false</masked>
      <name>B_AT_CutleryType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cc47377e-790b-4400-ac4a-3c145f9f954c</id>
      <masked>false</masked>
      <name>B_AT_DeskType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ba93c830-77d3-466d-8d43-628a6d841ef8</id>
      <masked>false</masked>
      <name>B_AT_DimensionalShape</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ba637160-7e0b-4169-a05e-a0830b7d26b5</id>
      <masked>false</masked>
      <name>B_AT_EnergyEfficiencyRating</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>dd46acc6-7136-4f87-a5aa-50907c056127</id>
      <masked>false</masked>
      <name>B_AT_Ergonomic</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>33897fd9-b410-4194-be79-5cfb0ea97666</id>
      <masked>false</masked>
      <name>B_AT_FillType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>deec39be-5cd1-4f78-bc35-51575dc704e6</id>
      <masked>false</masked>
      <name>B_AT_FurnitureStyle</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7d0c143a-f784-4c17-b0ff-1086ada37d27</id>
      <masked>false</masked>
      <name>B_AT_HeatingorCooling</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>82729e0e-e6f6-469e-88b2-d326ce4f383b</id>
      <masked>false</masked>
      <name>B_AT_HomeFragrance</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>bb1c25d1-656e-4548-baab-fe435663bfd5</id>
      <masked>false</masked>
      <name>B_AT_Mattresstype</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>90b72d79-f9d9-4163-80cb-5841ce21ff7e</id>
      <masked>false</masked>
      <name>B_AT_PrintIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>313a542f-7196-485a-a935-5a7e2d38d43b</id>
      <masked>false</masked>
      <name>B_AT_PrintorPattern</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a27836fd-6998-402c-a7bd-d8bf69161686</id>
      <masked>false</masked>
      <name>B_AT_RugType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ada2cb0e-d08e-4f1d-beaa-4ef5cab24f06</id>
      <masked>false</masked>
      <name>B_AT_TableandChairSettings</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>fc20116a-c517-42d8-8c93-9d69428c4a0f</id>
      <masked>false</masked>
      <name>B_AT_TowelType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>510da55e-9028-4bf4-8aba-8502321a7f71</id>
      <masked>false</masked>
      <name>B_AT_Usesuitability</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>51b060d9-3cce-42b1-9668-43cb53ca2812</id>
      <masked>false</masked>
      <name>B_AT_WaterEfficiencyRating</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f757bbc8-1b15-4d70-9257-c0c68a397235</id>
      <masked>false</masked>
      <name>B_AT_AdditivesType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0eeab781-2159-4b2e-bea8-c3fdef5db6f1</id>
      <masked>false</masked>
      <name>B_AT_CleaningAccessoryType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1b0f62eb-c12c-4040-a0aa-9bb63d51caaa</id>
      <masked>false</masked>
      <name>B_AT_CoverType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4e3ac6d6-e551-4b3d-bcd9-acacf07f7498</id>
      <masked>false</masked>
      <name>B_AT_EngineOilType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>200f8305-ce36-4110-a2e1-af2f7cdb9e2a</id>
      <masked>false</masked>
      <name>B_AT_GPS</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f66ffe26-5ce2-46c0-9ef5-11f967bc68df</id>
      <masked>false</masked>
      <name>B_AT_OutdoorFurnitureMaterial</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1f0fac96-cb3c-42e7-ac06-edd5ee8ec4e0</id>
      <masked>false</masked>
      <name>B_AT_PaperorCardType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1cbacea0-6318-4502-b205-66ae9a28bae0</id>
      <masked>false</masked>
      <name>B_AT_PaperSize</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>584cedef-e2c3-4e35-8240-5f28e18089f3</id>
      <masked>false</masked>
      <name>B_AT_PaperWeight</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>fc477d5a-dbd3-4c53-a7e4-7fe884fde055</id>
      <masked>false</masked>
      <name>B_AT_RollType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>16009bf8-08db-40b2-bf71-a6938af9017b</id>
      <masked>false</masked>
      <name>B_AT_ActivityUse</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>808d4f4d-d700-4e19-9b25-40869bbde434</id>
      <masked>false</masked>
      <name>B_AT_ArtPadType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>35d6e57e-dffc-4094-b3aa-bdf666e435c4</id>
      <masked>false</masked>
      <name>B_AT_BookCoverType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ad16b972-7f87-4ab7-87c0-12c2855b4c63</id>
      <masked>false</masked>
      <name>B_AT_ClipType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>84c1044a-bddd-4c30-9a7e-7b37889577e5</id>
      <masked>false</masked>
      <name>B_AT_EnvelopeType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1d8a763f-62fb-4557-a920-f880b5e58988</id>
      <masked>false</masked>
      <name>B_AT_ExerciseBookLineType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1e840f4d-c170-4e70-9d4a-7cf7108ab762</id>
      <masked>false</masked>
      <name>B_AT_LabelType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3eacd21d-4037-4598-bb19-310c331be86d</id>
      <masked>false</masked>
      <name>B_AT_Material</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>22c76cf2-5c66-4b34-b6a2-b81b5e4f613a</id>
      <masked>false</masked>
      <name>B_AT_PackSize</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ab715c64-fe7a-49e2-85b5-8c863017bc67</id>
      <masked>false</masked>
      <name>B_AT_PaintBrushType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>79271276-ca05-4af2-b701-ead36482cc99</id>
      <masked>false</masked>
      <name>B_AT_PaintType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>8940a2b1-51ab-48d9-9efb-efa75c5ea993</id>
      <masked>false</masked>
      <name>B_AT_PenType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3c350488-2665-421a-9055-b424e74606c5</id>
      <masked>false</masked>
      <name>B_AT_PencilType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0bebe096-a6fb-4ded-8590-65d9d9782b08</id>
      <masked>false</masked>
      <name>B_AT_ReportCoverType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2710f635-043e-4d86-b51f-949e3f1e55b6</id>
      <masked>false</masked>
      <name>B_AT_RingBinderType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b38447b9-7409-44c7-a967-34764e44b5de</id>
      <masked>false</masked>
      <name>B_AT_SchoolYear</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d3540f36-04ff-42f8-8626-2243e7de8568</id>
      <masked>false</masked>
      <name>B_AT_SprialBound</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3dbcc727-eea5-45d5-b4de-06a38a5b9db0</id>
      <masked>false</masked>
      <name>B_AT_StampType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>80f459e9-2d5e-4c68-a701-437be4b4b804</id>
      <masked>false</masked>
      <name>B_AT_StaplerType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d2e2e529-07a2-4390-824b-2da20689d914</id>
      <masked>false</masked>
      <name>B_AT_StationeryBookType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>558dd2bb-00ee-4661-8337-2193f4101b08</id>
      <masked>false</masked>
      <name>B_AT_STEAMSubject</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9991fac4-6492-4672-9df3-d8711619317d</id>
      <masked>false</masked>
      <name>B_AT_Subject</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c84fa460-1972-4c3d-afa0-1b1866ea77a0</id>
      <masked>false</masked>
      <name>B_AT_TapeType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>61af2cbf-64f8-406f-a0f6-d23e9f3d49e1</id>
      <masked>false</masked>
      <name>B_AT_WhiteboardType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c0efeb8b-3c78-4c7b-954d-280ba82985f3</id>
      <masked>false</masked>
      <name>B_AT_CableConnections</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c4b5d597-feb3-4c5a-89f8-2a35384ba887</id>
      <masked>false</masked>
      <name>B_AT_ConnectionPort</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>861a378b-5a84-4c7d-a724-f1cea35f3368</id>
      <masked>false</masked>
      <name>B_AT_DeviceType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ccfada62-1de9-4f4c-b9d6-163e96f2b512</id>
      <masked>false</masked>
      <name>B_AT_IMEIRequired</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>db7451c2-7602-40cd-b6f3-9a7869ceab52</id>
      <masked>false</masked>
      <name>B_AT_InkandTonerColours</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>49172921-7fd4-4b83-93b3-f5f5c5c8eb47</id>
      <masked>false</masked>
      <name>B_AT_ScreenSize</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>eeb6f4f3-f286-4333-beb4-d5543051479e</id>
      <masked>false</masked>
      <name>B_AT_ScreenType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>11ac4a64-4add-47cd-bc75-7e3b3f7d79f9</id>
      <masked>false</masked>
      <name>B_AT_TelcoNetwork</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>14c99f3b-c45d-4f0d-9ed3-9d552cdb1afd</id>
      <masked>false</masked>
      <name>B_AT_TouchScreen</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>91d41708-e118-4ee5-9eca-751726484993</id>
      <masked>false</masked>
      <name>B_AT_Age</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>154fa60a-ee7c-4a37-8ec4-9488ce78a441</id>
      <masked>false</masked>
      <name>B_AT_ToyType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>84b9567d-d99d-48de-aa54-cc52dc806be3</id>
      <masked>false</masked>
      <name>C_BarCode_Name1</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7bc16c70-bd1e-4fe0-a1ce-b80a669984c7</id>
      <masked>false</masked>
      <name>B_AT_ProductBarcode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7b192b6e-c012-4403-b151-d877fa13b3d4</id>
      <masked>false</masked>
      <name>B_AT_ProductBarcodeNumber</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>38432c05-8674-492c-b577-e34232213b5a</id>
      <masked>false</masked>
      <name>B_AT_BarcodeFormat</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a8bb719c-6ca8-4294-9903-9a42c58abe73</id>
      <masked>false</masked>
      <name>B_AT_BarcodeType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b624d73c-1c97-478a-98d2-d0c7c163f40a</id>
      <masked>false</masked>
      <name>C_BarCode_Name2</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()


WS.verifyResponseStatusCode(response, 200)

assertThat(response.getStatusCode()).isEqualTo(200)</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
