<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Composite_Item_Request_TC01_OLD</name>
   <tag></tag>
   <elementGuidId>12641e35-4084-4ded-9be1-2c17fbd8bae1</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>0</connectionTimeout>
   <followRedirects>true</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;\u003c?xml version\u003d\&quot;1.0\&quot; encoding\u003d\&quot;utf-8\&quot;?\u003e\n\u003cSTEP-ProductInformation ContextID\u003d\&quot;en-NZ\&quot; WorkspaceID\u003d\&quot;Main\&quot; UseContextLocale\u003d\&quot;false\&quot;\u003e\n\t\u003cProducts\u003e\n\t\t\u003cProduct UserTypeID\u003d\&quot;PPH_CompositeItem\&quot; ParentID\u003d\&quot;${C_ParentID}\&quot;\u003e\n\t\t\t\u003cName\u003e${C_Name}\u003c/Name\u003e\n\t\t\t\u003cClassificationReference Type\u003d\&quot;Product_To_BrandHierarchy\&quot;\u003e\n\t\t\t\t\u003cKeyValue KeyID\u003d\&quot;KEY_Brand\&quot;\u003e\n\t\t\t\t\tANTHEM\n\t\t\t\t\u003c/KeyValue\u003e\n\t\t\t\u003c/ClassificationReference\u003e\n\t\t\t\u003cClassificationReference ClassificationID\u003d\&quot;MERCH_L5_1308\&quot; Type\u003d\&quot;Product_To_MerchandiseHierarchy\&quot; /\u003e\n\t\t\t\u003cClassificationCrossReference ClassificationID\u003d\&quot;WSLHierarchy\&quot; Type\u003d\&quot;WSLOnlineDetails\&quot;\u003e\n\t\t\t\t\u003cMetaData\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductDescriptionWebstore\&quot;\u003e\n\t\t\t\t\t\t${C_WSL_AT_ProductDescriptionWebstore}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliveryMinimumDays\&quot;\u003e\n\t\t\t\t\t\t${C_WSL_AT_OnlineDeliveryMinimumDays}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_SoldOnlineIndicator\&quot; ID\u003d\&quot;${C_WSL_AT_SoldOnlineIndicator}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliveryMaximumDays\&quot;\u003e\n\t\t\t\t\t\t${C_WSL_AT_OnlineDeliveryMaximumDays}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebEnabled\&quot; ID\u003d\&quot;${C_WSL_AT_WebEnabled}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliverySizeOverride\&quot; ID\u003d\&quot;${C_WSL_AT_OnlineDeliverySizeOverride}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliverySizeDefault\&quot; ID\u003d\&quot;${C_WSL_AT_OnlineDeliverySizeDefault}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebItemSku\&quot;\u003e\n\t\t\t\t\t\t${C_WSL_AT_WebItemSku}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebExpiryDate\&quot;\u003e\n\t\t\t\t\t\t${C_WSL_AT_WebExpiryDate}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_FeaturesAndBenefits\&quot;\u003e\n\t\t\t\t\t\t${C_WSL_AT_FeaturesAndBenefits}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ClickAndCollectFlag\&quot; ID\u003d\&quot;${C_WSL_AT_ClickAndCollectFlag}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebClearanceIndicator\&quot; ID\u003d\&quot;${C_WSL_AT_WebClearanceIndicator}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebEffectiveDate\&quot;\u003e\n\t\t\t\t\t\t${C_WSL_AT_WebEffectiveDate}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003c/MetaData\u003e\n\t\t\t\u003c/ClassificationCrossReference\u003e\n\t\t\t\u003cClassificationCrossReference ClassificationID\u003d\&quot;TWLHierarchy\&quot; Type\u003d\&quot;TWLOnlineDetails\&quot;\u003e\n\t\t\t\t\u003cMetaData\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductDescriptionWebstore\&quot;\u003e\n\t\t\t\t\t\t${C_TWL_AT_ProductDescriptionWebstore}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliveryMinimumDays\&quot;\u003e\n\t\t\t\t\t\t${C_TWL_AT_OnlineDeliveryMinimumDays}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_SoldOnlineIndicator\&quot; ID\u003d\&quot;${C_TWL_AT_SoldOnlineIndicator}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliveryMaximumDays\&quot;\u003e\n\t\t\t\t\t\t${C_TWL_AT_OnlineDeliveryMaximumDays}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebEnabled\&quot; ID\u003d\&quot;${C_TWL_AT_WebEnabled}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliverySizeOverride\&quot; ID\u003d\&quot;${C_TWL_AT_OnlineDeliverySizeOverride}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OnlineDeliverySizeDefault\&quot; ID\u003d\&quot;${C_TWL_AT_OnlineDeliverySizeDefault}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebItemSku\&quot;\u003e\n\t\t\t\t\t\t${C_TWL_AT_WebItemSku}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebExpiryDate\&quot;\u003e\n\t\t\t\t\t\t${C_TWL_AT_WebExpiryDate}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_FeaturesAndBenefits\&quot;\u003e\n\t\t\t\t\t\t${C_TWL_AT_FeaturesAndBenefits}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ClickAndCollectFlag\&quot; ID\u003d\&quot;${C_TWL_AT_ClickAndCollectFlag}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebClearanceIndicator\&quot; ID\u003d\&quot;${C_TWL_AT_WebClearanceIndicator}\&quot; /\u003e\n\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_WebEffectiveDate\&quot;\u003e\n\t\t\t\t\t\t${C_TWL_AT_WebEffectiveDate}\n\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003c/MetaData\u003e\n\t\t\t\u003c/ClassificationCrossReference\u003e\n\t\t\t\u003cProductCrossReference Type\u003d\&quot;CompositeProduct_To_Product\&quot;\u003e\n\t\t\t\t\u003cKeyValue KeyID\u003d\&quot;KEY_Product\&quot;\u003e\n\t\t\t\t\t${CompositeProduct_To_Product}\n\t\t\t\t\u003c/KeyValue\u003e\n\t\t\t\u003c/ProductCrossReference\u003e\n\t\t\t\u003cValues\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_DangerousGoodsTransportIndicator\&quot; ID\u003d\&quot;${C_AT_DangerousGoodsTransportIndicator}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_HighRiskIndicator\&quot; ID\u003d\&quot;${C_AT_HighRiskIndicator}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_InStoreEndDate\&quot;\u003e\n\t\t\t\t\t${C_AT_InStoreEndDate}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_InStoreStartDate\&quot;\u003e\n\t\t\t\t\t${C_AT_InStoreStartDate}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PackagingFormat\&quot; ID\u003d\&quot;${C_AT_PackagingFormat}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ParallelImportCode\&quot; ID\u003d\&quot;${C_AT_ParallelImportCode}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_PreOrderAvailable\&quot; ID\u003d\&quot;${C_AT_PreOrderAvailable}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductImageURLIndicator\&quot; ID\u003d\&quot;${C_AT_ProductImageURLIndicator}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductName\&quot;\u003e\n\t\t\t\t\t${C_AT_ProductName}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductShortName\&quot;\u003e\n\t\t\t\t\t${C_AT_ProductShortName}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductStatus\&quot; ID\u003d\&quot;${C_AT_ProductStatus}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_RecallStatus\&quot; ID\u003d\&quot;${C_AT_RecallStatus}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShippingProductDepth\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t${C_AT_ShippingProductDepth}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShippingProductHeight\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t${C_AT_ShippingProductHeight}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShippingProductVolume\&quot; UnitID\u003d\&quot;unece.unit.MTQ\&quot;\u003e\n\t\t\t\t\t${C_AT_ShippingProductVolume}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShippingProductWeight\&quot; UnitID\u003d\&quot;unece.unit.KGM\&quot;\u003e\n\t\t\t\t\t${C_AT_ShippingProductWeight}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShippingProductWidth\&quot; UnitID\u003d\&quot;unece.unit.MMT\&quot;\u003e\n\t\t\t\t\t${C_AT_ShippingProductWidth}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_SupplierCode\&quot;\u003e\n\t\t\t\t\t${C_AT_SupplierCode}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_TUIItemKey\&quot;\u003e\n\t\t\t\t\t${C_AT_TUIItemKey}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_TUIProductKey\&quot;\u003e${C_AT_TUIProductKey}\u003c/Value\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_AssemblyAttribute\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${C_AT_AssemblyAttribute}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_BestBeforeDateIndicator\&quot; ID\u003d\&quot;${C_AT_BestBeforeDateIndicator}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_BetterCottonInitiative\&quot; ID\u003d\&quot;${C_AT_BetterCottonInitiative}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_Character\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${C_AT_Character}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_Colour\&quot; ID\u003d\&quot;${C_AT_Colour}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ColourFamily\&quot; ID\u003d\&quot;${C_AT_ColourFamily}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ForestStewardshipCouncil\&quot; ID\u003d\&quot;${C_AT_ForestStewardshipCouncil}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_Gender\&quot; ID\u003d\&quot;${C_AT_Gender}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_License\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${C_AT_License}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ReducetoSellIndicator\&quot; ID\u003d\&quot;${C_AT_ReducetoSellIndicator}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_Season\&quot; ID\u003d\&quot;${C_AT_Season}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ShelfLife\&quot;\u003e\n\t\t\t\t\t${C_AT_ShelfLife}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_Size\&quot; ID\u003d\&quot;${C_AT_Size}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_SchooltexProductType\&quot;\u003e\n\t\t\t\t\t${C_AT_SchooltexProductType}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_FabricContent\&quot;\u003e\n\t\t\t\t\t${C_AT_FabricContent}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_LegalAgeRestriction\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${C_AT_LegalAgeRestriction}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_GSTExempt\&quot; ID\u003d\&quot;${C_AT_GSTExempt}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_SafetyCheck\&quot; ID\u003d\&quot;${C_AT_SafetyCheck}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ArtistorAuthor\&quot;\u003e\n\t\t\t\t\t${C_AT_ArtistorAuthor}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_BookGenre\&quot; ID\u003d\&quot;${C_AT_BookGenre}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_MultimediaPackSize\&quot;\u003e\n\t\t\t\t\t${C_AT_MultimediaPackSize}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_NewRelease\&quot; ID\u003d\&quot;${C_AT_NewRelease}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_NewReleaseExpiryDate\&quot;\u003e\n\t\t\t\t\t${C_AT_NewReleaseExpiryDate}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_CalculatorType\&quot; ID\u003d\&quot;${C_AT_CalculatorType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_DVDGenre\&quot; ID\u003d\&quot;${C_AT_DVDGenre}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_GameGenre\&quot; ID\u003d\&quot;${C_AT_GameGenre}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_GamingSoftwareType\&quot; ID\u003d\&quot;${C_AT_GamingSoftwareType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_HeadphoneType\&quot; ID\u003d\&quot;${C_AT_HeadphoneType}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_HPSureSupplySKUCode\&quot;\u003e\n\t\t\t\t\t${C_AT_HPSureSupplySKUCode}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_iPhoneModel\&quot;\u003e\n\t\t\t\t\t${C_AT_iPhoneModel}\n\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_MusicGenre\&quot; ID\u003d\&quot;${C_AT_MusicGenre}\&quot; /\u003e\n\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_OperatingSystem\&quot; ID\u003d\&quot;${C_AT_OperatingSystem}\&quot; /\u003e\n\t\t\t\t\u003cMultiValue AttributeID\u003d\&quot;AT_PrinterType\&quot;\u003e\n\t\t\t\t\t\u003cValue ID\u003d\&quot;${C_AT_PrinterType}\&quot; /\u003e\n\t\t\t\t\u003c/MultiValue\u003e\n\t\t\t\u003c/Values\u003e\n\t\t\t\u003cDataContainers\u003e\n\t\t\t\t\u003cMultiDataContainer Type\u003d\&quot;DC_BarcodeType\&quot;\u003e\n\t\t\t\t\t\u003cDataContainer ID\u003d\&quot;${C_BarCode_Name}\&quot; Name\u003d\&quot;${C_BarCode_Name}\&quot;\u003e\n\t\t\t\t\t\t\u003cValues\u003e\n\t\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductBarcode\&quot;\u003e\n\t\t\t\t\t\t\t\t${C_AT_ProductBarcode}\n\t\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_BarcodeType\&quot; ID\u003d\&quot;P\&quot;\u003e\n\t\t\t\t\t\t\t\t${C_AT_BarcodeType}\n\t\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_ProductBarcodeNumber\&quot;\u003e\n\t\t\t\t\t\t\t\t${C_AT_ProductBarcodeNumber}\n\t\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\t\u003cValue AttributeID\u003d\&quot;AT_BarcodeFormat\&quot; ID\u003d\&quot;EAN\&quot;\u003e\n\t\t\t\t\t\t\t\t${C_AT_BarcodeFormat}\n\t\t\t\t\t\t\t\u003c/Value\u003e\n\t\t\t\t\t\t\u003c/Values\u003e\n\t\t\t\t\t\u003c/DataContainer\u003e\n\t\t\t\t\u003c/MultiDataContainer\u003e\n\t\t\t\u003c/DataContainers\u003e\n\t\t\u003c/Product\u003e\n\t\u003c/Products\u003e\n\u003c/STEP-ProductInformation\u003e\n&quot;,
  &quot;contentType&quot;: &quot;application/xml&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/octet-stream</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic QVJJOjEyMzQ=</value>
   </httpHeaderProperties>
   <maxResponseSize>0</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://mdmdev.thewarehousegroup.co.nz/restapiv2/inbound-integration-endpoints/IIEP_ProductDeltaTUI/upload-and-invoke?context=en-NZ&amp;workspace=Main</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>0</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>91445215-b2e2-4f4f-9c2f-553ddf7426a1</id>
      <masked>false</masked>
      <name>C_Name</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b5454c29-9ad6-4e8e-b3ea-7acc2bffab84</id>
      <masked>false</masked>
      <name>C_ParentID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>811bf540-9600-4922-9136-f5f0383d8d64</id>
      <masked>false</masked>
      <name>C_WSL_AT_ProductDescriptionWebstore</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2e1cfa03-31ef-481c-9bd9-3e7f97346632</id>
      <masked>false</masked>
      <name>C_WSL_AT_OnlineDeliveryMinimumDays</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0fd1684d-fb3b-4663-b89d-279556b3e35b</id>
      <masked>false</masked>
      <name>C_WSL_AT_SoldOnlineIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>5dc0d187-02fa-428d-8c5d-791b1be8facb</id>
      <masked>false</masked>
      <name>C_WSL_AT_OnlineDeliveryMaximumDays</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>dd59e563-1a29-4458-86c2-84eaebd4502f</id>
      <masked>false</masked>
      <name>C_WSL_AT_WebEnabled</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>16b3d144-977d-4778-a9b8-1f28af68d357</id>
      <masked>false</masked>
      <name>C_WSL_AT_OnlineDeliverySizeOverride</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2be013a9-7b96-4989-a25f-0dce1a1c6015</id>
      <masked>false</masked>
      <name>C_WSL_AT_OnlineDeliverySizeDefault</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b65be4bf-c65c-4d75-a250-a81d6be3b3d6</id>
      <masked>false</masked>
      <name>C_WSL_AT_WebItemSku</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>06f3b096-b2b4-4b45-8208-a061239eabf2</id>
      <masked>false</masked>
      <name>C_WSL_AT_WebExpiryDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>22c20c84-8558-4eef-ba23-7af6623ebfb9</id>
      <masked>false</masked>
      <name>C_WSL_AT_FeaturesAndBenefits</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>78954a96-643f-4f91-b19d-504e88b42b25</id>
      <masked>false</masked>
      <name>C_WSL_AT_ClickAndCollectFlag</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9abec568-35c5-4701-abdc-b3d13bb51057</id>
      <masked>false</masked>
      <name>C_WSL_AT_WebClearanceIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>99101a8c-1afd-4e48-a4ef-1ba1c551dfc6</id>
      <masked>false</masked>
      <name>C_WSL_AT_WebEffectiveDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6789638d-f61c-4b8d-9026-05cccb4e5949</id>
      <masked>false</masked>
      <name>C_TWL_AT_ProductDescriptionWebstore</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>409297b8-ab03-4911-9489-de7ea2a46fc1</id>
      <masked>false</masked>
      <name>C_TWL_AT_OnlineDeliveryMinimumDays</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4f5155e1-8b58-48b8-92ee-0e07eac74b0b</id>
      <masked>false</masked>
      <name>C_TWL_AT_SoldOnlineIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3e775a6a-1953-42fd-909b-0fcb546135e6</id>
      <masked>false</masked>
      <name>C_TWL_AT_OnlineDeliveryMaximumDays</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>20980eee-a280-4fe9-9298-fae5a228c7fa</id>
      <masked>false</masked>
      <name>C_TWL_AT_WebEnabled</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d0028fed-5326-4f01-bb38-7621689727bc</id>
      <masked>false</masked>
      <name>C_TWL_AT_OnlineDeliverySizeOverride</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>95768fee-5ca0-48ac-83ce-91fed1b05358</id>
      <masked>false</masked>
      <name>C_TWL_AT_OnlineDeliverySizeDefault</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f223a5ec-7b85-4a11-b796-192d2b2b0516</id>
      <masked>false</masked>
      <name>C_TWL_AT_WebItemSku</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2490c261-7211-4096-977c-c5a6182b5487</id>
      <masked>false</masked>
      <name>C_TWL_AT_WebExpiryDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>afc56266-142f-49bb-8d12-136a864df7d6</id>
      <masked>false</masked>
      <name>C_TWL_AT_FeaturesAndBenefits</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>86b5bbab-67e4-4fb7-a562-eb3f35748c19</id>
      <masked>false</masked>
      <name>C_TWL_AT_ClickAndCollectFlag</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1360dfe6-cdbc-419c-bb0d-46d4fd80d526</id>
      <masked>false</masked>
      <name>C_TWL_AT_WebClearanceIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2f91458b-7ba5-4674-b281-88055171769b</id>
      <masked>false</masked>
      <name>C_TWL_AT_WebEffectiveDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d8c87258-b63e-454e-bebc-7bc5271be010</id>
      <masked>false</masked>
      <name>CompositeProduct_To_Product</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>46014859-af4a-4fd0-a38b-2bdded8f7281</id>
      <masked>false</masked>
      <name>C_AT_DangerousGoodsTransportIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0ef78cb6-913e-4e21-ab26-3494b998cde5</id>
      <masked>false</masked>
      <name>C_AT_HighRiskIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d3ca3479-209b-4a60-8034-5d2aacb166ab</id>
      <masked>false</masked>
      <name>C_AT_InStoreEndDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4b8b490f-e2f7-4d98-9e2a-a681c40c4129</id>
      <masked>false</masked>
      <name>C_AT_InStoreStartDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7698b904-584f-4861-b52e-6faee817f29f</id>
      <masked>false</masked>
      <name>C_AT_PackagingFormat</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0b148bb4-9e9a-402f-89c5-a9ac50deb171</id>
      <masked>false</masked>
      <name>C_AT_ParallelImportCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a217b564-c70c-408e-b71b-cb64c4b5fc79</id>
      <masked>false</masked>
      <name>C_AT_PreOrderAvailable</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9585d9c2-ce75-491b-a6f5-7ce2d723518c</id>
      <masked>false</masked>
      <name>C_AT_ProductImageURLIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cd6ffd01-eb8d-480d-8a14-3e110415b8ff</id>
      <masked>false</masked>
      <name>C_AT_ProductName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>981278d1-76c7-4537-abba-6445296c656d</id>
      <masked>false</masked>
      <name>C_AT_ProductShortName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>8aa3057e-3e7a-490b-a05c-ba0d7b1c7068</id>
      <masked>false</masked>
      <name>C_AT_ProductStatus</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>76730489-772b-4d53-a158-7ca177a2b3a2</id>
      <masked>false</masked>
      <name>C_AT_RecallStatus</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>488c2927-974c-4938-92d3-09442ac3851e</id>
      <masked>false</masked>
      <name>C_AT_ShippingProductDepth</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2b213ea4-6579-4bf7-be98-7d671f5f1a6f</id>
      <masked>false</masked>
      <name>C_AT_ShippingProductHeight</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2c9f24cd-51f0-4ba6-ac2f-674463331cd0</id>
      <masked>false</masked>
      <name>C_AT_ShippingProductVolume</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>77f21283-bfc9-4f93-a7a0-83891dfe9df6</id>
      <masked>false</masked>
      <name>C_AT_ShippingProductWeight</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>84a3cf44-c26a-4c2e-8046-6a8d9d41283e</id>
      <masked>false</masked>
      <name>C_AT_ShippingProductWidth</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d06b29ad-de74-4cc2-860d-c85290043b3b</id>
      <masked>false</masked>
      <name>C_AT_SupplierCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>62b2d4f6-6dfc-4658-997a-df140bec1c60</id>
      <masked>false</masked>
      <name>C_AT_TUIItemKey</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1051e177-bf20-4bd8-a9c8-8a8f4404c8a7</id>
      <masked>false</masked>
      <name>C_AT_TUIProductKey</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a4247f49-4b5e-4197-a720-b7ff4f8c2ccf</id>
      <masked>false</masked>
      <name>C_AT_AssemblyAttribute</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e5d975e3-4b0d-442e-b333-969e21706c34</id>
      <masked>false</masked>
      <name>C_AT_BestBeforeDateIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7538b139-4da5-469e-bb54-56a4cc869bff</id>
      <masked>false</masked>
      <name>C_AT_BetterCottonInitiative</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b9755aea-a850-47ed-9ec1-3fc9f4bb07ab</id>
      <masked>false</masked>
      <name>C_AT_Character</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c726b64c-0f9d-423f-b415-a412c67880ab</id>
      <masked>false</masked>
      <name>C_AT_Colour</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>8c6924dd-13b3-4b08-a2d5-e55c57eed222</id>
      <masked>false</masked>
      <name>C_AT_ColourFamily</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ded6a60d-59fc-4149-8238-62891171f9b6</id>
      <masked>false</masked>
      <name>C_AT_ForestStewardshipCouncil</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>688a225e-ec87-4126-a747-325121266ed7</id>
      <masked>false</masked>
      <name>C_AT_Gender</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0b950599-380d-42ee-b090-83ffb467464e</id>
      <masked>false</masked>
      <name>C_AT_License</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c1928df4-4aca-4924-98d9-0a769582f623</id>
      <masked>false</masked>
      <name>C_AT_ReducetoSellIndicator</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4d78e692-8ccf-4bf6-a028-3b9e714fd92f</id>
      <masked>false</masked>
      <name>C_AT_Season</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>769db7b2-506c-45d7-a3f4-e2ca67e3f4ab</id>
      <masked>false</masked>
      <name>C_AT_ShelfLife</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>691a07d6-c729-4173-8ea8-9e6bfce7bd93</id>
      <masked>false</masked>
      <name>C_AT_Size</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>03d2269a-7aba-42d2-aba7-0fbe47e94470</id>
      <masked>false</masked>
      <name>C_AT_SchooltexProductType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>de140ac4-00c9-4c5b-893a-a5eef2446670</id>
      <masked>false</masked>
      <name>C_AT_FabricContent</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b5e2683e-9fcf-4931-8687-e1b221399a7d</id>
      <masked>false</masked>
      <name>C_AT_LegalAgeRestriction</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f5967162-e7a2-4f8e-a9e1-8ee6d6636a0a</id>
      <masked>false</masked>
      <name>C_AT_GSTExempt</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>23177886-8e0a-4dc2-bcf2-2e61ec2ceb06</id>
      <masked>false</masked>
      <name>C_AT_SafetyCheck</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2cc69008-ad95-4b0d-85f5-bfe7f38f1e9e</id>
      <masked>false</masked>
      <name>C_AT_ArtistorAuthor</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cc3a1d2d-06a4-499f-aa57-556f6443e22a</id>
      <masked>false</masked>
      <name>C_AT_BookGenre</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0f784b5f-aacb-4c25-ad58-4c132baafef2</id>
      <masked>false</masked>
      <name>C_AT_MultimediaPackSize</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>faf996b1-cc81-42b0-a8cf-4e3845f3d687</id>
      <masked>false</masked>
      <name>C_AT_NewRelease</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cdc79ef4-2180-41f3-afae-28dc1aa7d042</id>
      <masked>false</masked>
      <name>C_AT_NewReleaseExpiryDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>93c1f105-9afa-4554-bc5c-15f8b09e760c</id>
      <masked>false</masked>
      <name>C_AT_CalculatorType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f097be3a-ed54-4010-aa0c-58784a7c817e</id>
      <masked>false</masked>
      <name>C_AT_DVDGenre</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9bf712b5-39a0-45d0-a621-245281326ab1</id>
      <masked>false</masked>
      <name>C_AT_GameGenre</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ed211637-6beb-44a5-8751-ef5f478ef95a</id>
      <masked>false</masked>
      <name>C_AT_GamingSoftwareType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>77865a84-17d0-4291-9710-111782bb2912</id>
      <masked>false</masked>
      <name>C_AT_HeadphoneType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3df62630-4d9f-4abe-a70e-cc6d8a977d7a</id>
      <masked>false</masked>
      <name>C_AT_HPSureSupplySKUCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>5c19f88d-58fe-444c-99b7-1b1f889561c2</id>
      <masked>false</masked>
      <name>C_AT_iPhoneModel</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>79cd8d43-4617-4245-aeff-ca827c28ab97</id>
      <masked>false</masked>
      <name>C_AT_MusicGenre</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cd33941f-3f91-4601-9fc7-756bdb29391d</id>
      <masked>false</masked>
      <name>C_AT_OperatingSystem</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>5c1889c1-1c21-40db-a779-5b532d2b166f</id>
      <masked>false</masked>
      <name>C_AT_PrinterType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d8bb080e-98e3-462e-b803-b1af1b01317f</id>
      <masked>false</masked>
      <name>C_DC_BarcodeType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b3b7b9c4-2076-432f-9d0a-af195af803ff</id>
      <masked>false</masked>
      <name>C_AT_ProductBarcode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7fcb042c-1db9-4ee3-9da9-b19bc683b90c</id>
      <masked>false</masked>
      <name>C_AT_BarcodeType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3f2c4db5-d960-4056-9880-c3c5505dfd4c</id>
      <masked>false</masked>
      <name>C_AT_ProductBarcodeNumber</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>5b95a4cf-6fda-4178-bb54-7b92cc5cf2ee</id>
      <masked>false</masked>
      <name>C_AT_BarcodeFormat</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>84042685-36ac-4431-b7da-ec742a62bf76</id>
      <masked>false</masked>
      <name>variable</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()


WS.verifyResponseStatusCode(response, 200)

assertThat(response.getStatusCode()).isEqualTo(200)</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
